### ISSUE TITLE
Many failed resque jobs in when receiving messages (and therefore many missed messages)

### ISSUE THREAD

**Issue by tomka** [diaspora/diaspora#4035]
Is see many failed Resque jobs on my pod (runs on up-to-date master). They all state that "parent is nil" and those messages referred to in the logs aren't actually available on my pod. I just realized that I got those message for a few months now. This is an example message:

``` Worker
my-hidden-host-name:13648 on receive at about an hour ago
    Retry or Remove

Class
   Jobs::ReceiveUnencryptedSalmon
Arguments

    "    <?xml version='1.0' encoding='UTF-8'?>\n    <diaspora xmlns=\"https://joindiaspora.com/protocol\" xmlns:me=\"http://salmon-protocol.org/ns/magic-env\">\n      <header>    <author_id>jaywink@iliketoast.net</author_id>\n</header>\n      <me:env>\n  <me:data type='application/xml'>ICAgICAgICAgIDxYTUw-CiAgICAgICAgICA8cG9zdD48Y29tbWVudD4KICA8Z3VpZD4yODZhMGNlN2QwNzkxMTRiPC9ndWlkPgogIDxwYXJlbnRfZ3VpZD5kNjc4OWM3YzZiNmNjZGZhPC9wYXJlbnRfZ3VpZD4KICA8cGFyZW50X2F1dGhvcl9zaWduYXR1cmU-ZFpXMExvQU92OEtrVTRZVHVTNE5oeUJYejFBZnpDVUdnOGZqN0pZTWE1NllJNFdSa3JmRzZ0SStCdjZYU0J1OHlqbCtrWk1QdHhTL1dtaTdSNkQvbmViZEZFNlIrZHh0U05vTFRKdDJGQjBGbjdCazBvQ2pxMTJoWllGanlBcVFvTWJKVGdYQjZEYVAwMmFXRW0wTE0yN3lWK2FuZC9DLzVHL0FmQVJBNlk3Vi9vSWVQTVpOOWpVT3NIcU1mWkNuWFNZaVVuMVFWZGVLVi9oMTA1QU1wM1ZVbTR2MUtXUkIxSUFHL0hTRVVCUFVFdWpYWFVSeG9uN2VNYkdMd0ZYVURzM29XSW5kejd1dzZvR1oxSmFoS0FSUHZtT25idDFIWUFCNEdLMXRPZTArOEFKaGdLdlZDZWhxMnFyYy9QT0x2Q0k4cE5ib2NKNzZtS2NPbjdCQTVWRE5wZDZFQTQ2VytCREFCeElPZWJzek82aCs0ZE11MnlQaHZTeDdOc3V6OVl1ZXRqY3VkUk1JY0VqdzAvSDVTS3ZWMmRYNk1YRmZNd29hVWVDRTNzYzhKSkhQTmNxSzE3bnM5TmpZbitCMXpkZ0xyQUk4c3lmSWN4YVpKVlB3NDVTS3RUb0p1c1o1anI2V3dLMWwwTy9OSTFyWVNaUGtXQUlPWFZBVDhrdThORjIveWMwMWRLVDZGMVZ0cFVmYlBKU1g4U0ZJTVJyLzVHa3NFd3dlbTRXazRab21EbWhLcHJJNkRMVzJCSE5CaVNjSkdMVzhvdWVmbGFCTktsbGFjTGNrRG92ZDFWVFZ4M3JNYUxXRGJaV1psZVdVVVJpQkZBZnFlOTVSeGtZNlVkQ3dzK3AzQnFhNSs3TjFNUmN2MEVZWm9jb0E5TFpjNzd1MDB5N3hpU2c9PC9wYXJlbnRfYXV0aG9yX3NpZ25hdHVyZT4KICA8YXV0aG9yX3NpZ25hdHVyZT5kWlcwTG9BT3Y4S2tVNFlUdVM0Tmh5Qlh6MUFmekNVR2c4Zmo3SllNYTU2WUk0V1JrcmZHNnRJK0J2NlhTQnU4eWpsK2taTVB0eFMvV21pN1I2RC9uZWJkRkU2UitkeHRTTm9MVEp0MkZCMEZuN0JrMG9DanExMmhaWUZqeUFxUW9NYkpUZ1hCNkRhUDAyYVdFbTBMTTI3eVYrYW5kL0MvNUcvQWZBUkE2WTdWL29JZVBNWk45alVPc0hxTWZaQ25YU1lpVW4xUVZkZUtWL2gxMDVBTXAzVlVtNHYxS1dSQjFJQUcvSFNFVUJQVUV1alhYVVJ4b243ZU1iR0x3RlhVRHMzb1dJbmR6N3V3Nm9HWjFKYWhLQVJQdm1PbmJ0MUhZQUI0R0sxdE9lMCs4QUpoZ0t2VkNlaHEycXJjL1BPTHZDSThwTmJvY0o3Nm1LY09uN0JBNVZETnBkNkVBNDZXK0JEQUJ4SU9lYnN6TzZoKzRkTXUyeVBodlN4N05zdXo5WXVldGpjdWRSTUljRWp3MC9INVNLdlYyZFg2TVhGZk13b2FVZUNFM3NjOEpKSFBOY3FLMTduczlOalluK0IxemRnTHJBSThzeWZJY3hhWkpWUHc0NVNLdFRvSnVzWjVqcjZXd0sxbDBPL05JMXJZU1pQa1dBSU9YVkFUOGt1OE5GMi95YzAxZEtUNkYxVnRwVWZiUEpTWDhTRklNUnIvNUdrc0V3d2VtNFdrNFpvbURtaEtwckk2RExXMkJITkJpU2NKR0xXOG91ZWZsYUJOS2xsYWNMY2tEb3ZkMVZUVngzck1hTFdEYlpXWmxlV1VVUmlCRkFmcWU5NVJ4a1k2VWRDd3MrcDNCcWE1KzdOMU1SY3YwRVlab2NvQTlMWmM3N3UwMHk3eGlTZz08L2F1dGhvcl9zaWduYXR1cmU-CiAgPHRleHQ-WWVhaCBpdCB3aWxsIGJlIGluIHRoZSBuZXh0IHJlbGVhc2UuIEkgcnVuIG15IHBvZCBvbiBkZXYgdW5zdGFibGUgY29kZSA6UDwvdGV4dD4KICA8ZGlhc3BvcmFfaGFuZGxlPmpheXdpbmtAaWxpa2V0b2FzdC5uZXQ8L2RpYXNwb3JhX2hhbmRsZT4KPC9jb21tZW50PjwvcG9zdD4KICAgICAgICAgIDwvWE1MPgo=</me:data>\n  <me:encoding>base64url</me:encoding>\n  <me:alg>RSA-SHA256</me:alg>\n  <me:sig>hv6ccpVzyCYVnhNbv7K66yKBzNIuezp4QHj0JqYhG3sdQUNWB1qqEfEfKMuTA49X5ylZDQLawNreMS4r5x-MAqn9hQEuqz9moF5nCh0Lg4oxIEKMqKD_ZPd6oOnorlRQJzyfOEupLGfgqTDfdJABHvtIeD041qnhz432SkHlYZCtmFS7dwoLmiEEO28TTA5_kECMbznhpYlf5HwC6queYoGxUEtrkWsyJcwDVXdpThX-hALzYOf4Kuo7nnOsadwydmp3BJIz6sWOR-nwmxz36QTOf4cspb3vcoyJmMl2OIAkIjUAzk6szhVYUzzwx1XThtViDu5oAdUIUdHdX1SsElRg-KdStwNSUqICi2J-OCGM-FZQsqWBKWhqL5f24iA5qy6fGTxECEYOz5HgdEPzfGBYQKQG3yUSq8nTm5ESLSDGoYYOvUNFOz5_f1yShp_OaEuElXEn5L-47ibGjArFmwsBJOwRcs81AazgM8WJ_7lB0o3JTxPcWHSBOOAXpxPGUkFAFoXzsWia0KDXzmBlYJarN_g-sdpQuKELbdFBhoDc2HvPa_OHcv6FkSeFaYbfZUhzbVh15Q8KtwQ7wcVcWBF5GGcQ1N-RV8EoUdUFDpzVM-ibHF_cjcGjvqQ30Q9MBVqbz6hKGiTs66kOk1FTp2Qvc4u6eBT2WdGnfnqbdiA=</me:sig>\n  </me:env>\n\n    </diaspora>\n"

Exception
    RuntimeError
Error
    Comment#parent_author delegated to parent.author, but parent is nil: #<Comment id: nil, text: "Yeah it will be in the next release. I run my pod o...", commentable_id: nil, author_id: 7593, guid: "286a0ce7d079114b", author_signature: "dZW0LoAOv8KkU4YTuS4NhyBXz1AfzCUGg8fj7JYMa56YI4WRkrf...", parent_author_signature: "dZW0LoAOv8KkU4YTuS4NhyBXz1AfzCUGg8fj7JYMa56YI4WRkrf...", created_at: nil, updated_at: nil, likes_count: 0, commentable_type: nil>

    /home/tom/dev/diaspora/lib/diaspora/relayable.rb:24:in `rescue in parent_author'
    /home/tom/dev/diaspora/lib/diaspora/relayable.rb:21:in `parent_author'
    /home/tom/dev/diaspora/lib/postzord/receiver/public.rb:67:in `xml_author'
    /home/tom/dev/diaspora/lib/postzord/receiver.rb:15:in `author_does_not_match_xml_author?'
    /home/tom/dev/diaspora/lib/postzord/receiver/public.rb:55:in `save_object'
    /home/tom/dev/diaspora/lib/postzord/receiver/public.rb:26:in `receive!'
    /home/tom/dev/diaspora/lib/postzord/receiver.rb:11:in `perform!'
    /home/tom/dev/diaspora/app/models/jobs/receive_unencrypted_salmon.rb:14:in `perform'
```
##

**Comment by Flaburgan** [comment]
We just reproduced the problem between diaspora-fr.org and diaspote.org.

The [original message](https://diaspote.org/posts/b0693a809cce013293530af502428d70) was posted on **diaspote.org** by dada@diaspote.org. 
Here is how the message appears [on diaspora-fr.org](https://diaspora-fr.org/posts/b0693a809cce013293530af502428d70).

As you can see, some comments posted on diaspora-fr.org never reached diaspote.org, for example [this one](https://diaspora-fr.org/posts/1051182#b2e157e09f5201324e101e696c267a28).

Here is the production.log when the comment was posted on diaspora-fr.org:
```
Started POST "/posts/1051182/comments" for X.X.X.X at 2015-02-25 20:30:37 +0100
Processing by CommentsController#create as JSON
  Parameters: {"text"=>"[FILTERED]", "post_id"=>"1051182", "comment"=>{"text"=>"[FILTERED]"}}
{:event=>:sign_with_key, :status=>:complete}
user:9 dispatching Participation:b2d94f409f5201324e101e696c267a28
{:event=>:sign_with_key, :status=>:complete}
event=http_multi_fail sender_id=9 url=https://diaspote.org/receive/public return_code=ssl_cacert_badfile
user:9 dispatching Comment:b2e157e09f5201324e101e696c267a28
Completed 201 Created in 183ms (Views: 6.7ms | ActiveRecord: 76.8ms)
event=http_multi_fail sender_id=9 url=https://diaspote.org/receive/public return_code=ssl_cacert_badfile

I tried to grep comment and participation guid in the sidekiq.log file but found nothing, what should I search for?

Also, @dadall could please check the diaspote.org logs and tell me if you have anything related to this comment (b2e157e09f5201324e101e696c267a28) and participation (b2d94f409f5201324e101e696c267a28)?

**Comment by dadall** [comment]
@Flaburgan : I have nothing related to b2e157e09f5201324e101e696c267a28. What is the problem with my SSL Cert ? It works perfectly since weeks now. 

I'm still receiving messages on my post, it really seems to be a random problem :/

**Comment by jhass** [comment]
You mean you've seen it. We still do lack a way to reproduce it.

**Comment by Flaburgan** [comment]
Does that error message mean anything to you @jhass?

**Comment by jhass** [comment]
Sounds like a configuration issue: http://erdani.com/d/library/etc/c/curl/curl_error.ssl_cacert_badfile.html

**Comment by Flaburgan** [comment]
Well, I reach diaspote.org without problem:
```
curl -I -v https://diaspote.org
* Rebuilt URL to: https://diaspote.org/
* Adding handle: conn: 0x363c020
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x363c020) send_pipe: 1, recv_pipe: 0
* About to connect() to diaspote.org port 443 (#0)
*   Trying 149.91.83.42...
* Connected to diaspote.org (149.91.83.42) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-SHA
* Server certificate:
* 	 subject: C=FR; CN=www.diaspote.org; emailAddress=webmaster@diaspote.org
* 	 start date: 2015-01-22 05:34:13 GMT
* 	 expire date: 2016-01-22 21:13:11 GMT
* 	 subjectAltName: diaspote.org matched
* 	 issuer: C=IL; O=StartCom Ltd.; OU=Secure Digital Certificate Signing; CN=StartCom Class 1 Primary Intermediate Server CA
* 	 SSL certificate verify ok.
> HEAD / HTTP/1.1
> User-Agent: curl/7.32.0
> Host: diaspote.org
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Thu, 26 Feb 2015 14:51:43 GMT
Date: Thu, 26 Feb 2015 14:51:43 GMT
< Status: 200 OK
Status: 200 OK
< Strict-Transport-Security: max-age=31536000
Strict-Transport-Security: max-age=31536000
< X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< X-Diaspora-Version: head-p3a0857b4
X-Diaspora-Version: head-p3a0857b4
< X-Git-Update: 2015-02-23 16:37:54 +0100
X-Git-Update: 2015-02-23 16:37:54 +0100
< X-Git-Revision: 3a0857b4bfd4e021d304c164be731eca5a5a7346
X-Git-Revision: 3a0857b4bfd4e021d304c164be731eca5a5a7346
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< ETag: "f42b27cf493ba8e74a7d8cd0d0d014a6"
ETag: "f42b27cf493ba8e74a7d8cd0d0d014a6"
< Cache-Control: max-age=0, private, must-revalidate
Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: 9015a672-997b-4cfc-9b90-a27b37bffbc4
X-Request-Id: 9015a672-997b-4cfc-9b90-a27b37bffbc4
< X-Runtime: 0.134361
X-Runtime: 0.134361
< Vary: Accept-Encoding
Vary: Accept-Encoding
< Set-Cookie: _diaspora_session=R2RSZU9Oay9IWDJlRjhwZUdBSkxBcDlNTUovNU0yMC84VlNtWEhqOStQV01XWDY1b2ZMNDhZYTNOSUNQYVY0WStmUU5tczFESnVyaUUxT0U3VSsyb1RqYjhtcE5paStkQ0YyV3ZhODQ1S1FiUlpkY1N5eUJTOHlMaTlSY1h0V1NyaTdxWitLNzE3TU5kS2p0eU1FREUrT1pGS2ovTEgxNGZYSnF1bmdTMXgxTnNzb2I4Q3cxbE1DdGVmdXpMZmt4LS1oZDlIS3VqWXY2RGdESGNPa2YrTFBnPT0%3D--e00857cc0d31d20894bfd5368259c0477fba2727; path=/; secure
Set-Cookie: _diaspora_session=R2RSZU9Oay9IWDJlRjhwZUdBSkxBcDlNTUovNU0yMC84VlNtWEhqOStQV01XWDY1b2ZMNDhZYTNOSUNQYVY0WStmUU5tczFESnVyaUUxT0U3VSsyb1RqYjhtcE5paStkQ0YyV3ZhODQ1S1FiUlpkY1N5eUJTOHlMaTlSY1h0V1NyaTdxWitLNzE3TU5kS2p0eU1FREUrT1pGS2ovTEgxNGZYSnF1bmdTMXgxTnNzb2I4Q3cxbE1DdGVmdXpMZmt4LS1oZDlIS3VqWXY2RGdESGNPa2YrTFBnPT0%3D--e00857cc0d31d20894bfd5368259c0477fba2727; path=/; secure
< Via: 1.1 diaspote.org
Via: 1.1 diaspote.org

< 
* Connection #0 to host diaspote.org left intact
```

**Comment by jhass** [comment]
Yeah, I suspect your `certificate_authorities` setting points to garbage.

**Comment by Flaburgan** [comment]
`certificate_authorities: '/etc/ssl/certs/ca-certificates.crt'` and the certificates are there. This is my production pod, I would have noticed that before ;)

However, curl doesn't look to have the c-ares even if it has AsynchDNS:
```
curl 7.32.0 (x86_64-pc-linux-gnu) libcurl/7.32.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 libssh2/1.2.8 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN Largefile NTLM NTLM_WB SSL libz TLS-SRP
```
Is that a problem? I used @jaywink's  ppa to upgrade curl on Ubuntu 12.04 LTS.

**Comment by jaywink** [comment]
Am I to understand from [this test](https://sslcheck.globalsign.com/en_US/sslcheck?host=diaspote.org#149.91.83.42-srv-reg-cert-ssl-misc) that diaspote.org doesn't send the root CA correctly? Totally not an expert, but @dadall can you check your `certificate_authorities` setting points to a correct file AND it is readable by web server?

**Comment by jaywink** [comment]
Also, I wonder if turning on [this](https://github.com/diaspora/diaspora/blob/develop/config/diaspora.yml.example#L439) would help for debugging?

**Comment by jhass** [comment]
turning that on on a prod pod will just cover you completely in debug output  :P

`certificate_authorities` controls which CAs your pod trusts when making *outgoing* connections, that's all.

**Comment by dadall** [comment]
I did that : https://www.startssl.com/?app=21

Do I miss something ?

**Comment by AugierLe42e** [comment]
May I remind you that I proposed [a solution to manage these kind of problems](https://gist.github.com/AugierLe42e/41f15c5fee6c3c666db7) ?

**Comment by Flaburgan** [comment]
With the new federation gem installed in both diaspote and diaspora-fr, I guess it's now time to redo some tests @dadall

**Comment by SuperTux88** [comment]
Is this still a problem? Or can we close it?

**Comment by svbergerem** [comment]
Looks like we can close this issue.
