### ISSUE TITLE
Can't load schema into postgresql db

### ISSUE THREAD

**Issue by Finn10111** [diaspora/diaspora#4327]
Hi,

I am using CentOS 6.4 with PostgreSQL 8.4.13 and trying to install diaspora on it. I have created a PostgreSQL user and dabtabase and then I tried to initialize the database with the given schema:

```
$ RAILS_ENV=production DB=postgres bundle exec rake db:create db:schema:load
(in /var/www/vhosts/example.org/diaspora)
diaspora_production already exists
[RailsAdmin] RailsAdmin initialization disabled by default. Pass SKIP_RAILS_ADMIN_INITIALIZER=false if you need it.
Rack::SSL is enabled
-- create_table("account_deletions", {:force=>true})
HINWEIS:  CREATE TABLE erstellt implizit eine Sequenz »account_deletions_id_seq« für die »serial«-Spalte »account_deletions.id«
HINWEIS:  CREATE TABLE / PRIMARY KEY erstellt implizit einen Index »account_deletions_pkey« für Tabelle »account_deletions«
   -> 0.3284s
-- create_table("aspect_memberships", {:force=>true})
HINWEIS:  CREATE TABLE erstellt implizit eine Sequenz »aspect_memberships_id_seq« für die »serial«-Spalte »aspect_memberships.id«
HINWEIS:  CREATE TABLE / PRIMARY KEY erstellt implizit einen Index »aspect_memberships_pkey« für Tabelle »aspect_memberships«
   -> 0.0664s
-- add_index("aspect_memberships", ["aspect_id", "contact_id"], {:name=>"index_aspect_memberships_on_aspect_id_and_contact_id", :unique=>true})
   -> 0.0748s
-- add_index("aspect_memberships", ["aspect_id"], {:name=>"index_aspect_memberships_on_aspect_id"})
   -> 0.0749s
-- add_index("aspect_memberships", ["contact_id"], {:name=>"index_aspect_memberships_on_contact_id"})
   -> 0.0666s
-- create_table("aspect_visibilities", {:force=>true})
HINWEIS:  CREATE TABLE erstellt implizit eine Sequenz »aspect_visibilities_id_seq« für die »serial«-Spalte »aspect_visibilities.id«
HINWEIS:  CREATE TABLE / PRIMARY KEY erstellt implizit einen Index »aspect_visibilities_pkey« für Tabelle »aspect_visibilities«
   -> 0.0730s
-- add_index("aspect_visibilities", ["aspect_id"], {:name=>"index_aspect_visibilities_on_aspect_id"})
   -> 0.0601s
-- add_index("aspect_visibilities", ["shareable_id", "shareable_type", "aspect_id"], {:name=>"shareable_and_aspect_id"})
   -> 0.0915s
-- add_index("aspect_visibilities", ["shareable_id", "shareable_type"], {:name=>"index_aspect_visibilities_on_shareable_id_and_shareable_type"})
   -> 0.0665s
-- create_table("aspects", {:force=>true})
HINWEIS:  CREATE TABLE erstellt implizit eine Sequenz »aspects_id_seq« für die »serial«-Spalte »aspects.id«
HINWEIS:  CREATE TABLE / PRIMARY KEY erstellt implizit einen Index »aspects_pkey« für Tabelle »aspects«
   -> 0.1003s
-- add_index("aspects", ["user_id", "contacts_visible"], {:name=>"index_aspects_on_user_id_and_contacts_visible"})
   -> 0.0747s
-- add_index("aspects", ["user_id"], {:name=>"index_aspects_on_user_id"})
   -> 0.0667s
-- create_table("blocks", {:force=>true})
HINWEIS:  CREATE TABLE erstellt implizit eine Sequenz »blocks_id_seq« für die »serial«-Spalte »blocks.id«
HINWEIS:  CREATE TABLE / PRIMARY KEY erstellt implizit einen Index »blocks_pkey« für Tabelle »blocks«
   -> 0.0665s
-- create_table("comments", {:force=>true})
HINWEIS:  CREATE TABLE erstellt implizit eine Sequenz »comments_id_seq« für die »serial«-Spalte »comments.id«
HINWEIS:  CREATE TABLE / PRIMARY KEY erstellt implizit einen Index »comments_pkey« für Tabelle »comments«
   -> 0.1169s
-- add_index("comments", ["author_id"], {:name=>"index_comments_on_person_id"})
   -> 0.1998s
-- add_index("comments", ["commentable_id", "commentable_type"], {:name=>"index_comments_on_commentable_id_and_commentable_type"})
   -> 0.0664s
-- add_index("comments", ["guid"], {:name=>"index_comments_on_guid", :unique=>true})
   -> 0.0667s
-- create_table("contacts", {:force=>true})
HINWEIS:  CREATE TABLE erstellt implizit eine Sequenz »contacts_id_seq« für die »serial«-Spalte »contacts.id«
HINWEIS:  CREATE TABLE / PRIMARY KEY erstellt implizit einen Index »contacts_pkey« für Tabelle »contacts«
   -> 0.0666s
-- add_index("contacts", ["person_id"], {:name=>"index_contacts_on_person_id"})
   -> 0.0914s
-- add_index("contacts", ["user_id", "person_id"], {:name=>"index_contacts_on_user_id_and_person_id", :unique=>true})
   -> 0.0663s
-- create_table("conversation_visibilities", {:force=>true})
HINWEIS:  CREATE TABLE erstellt implizit eine Sequenz »conversation_visibilities_id_seq« für die »serial«-Spalte »conversation_visibilities.id«
HINWEIS:  CREATE TABLE / PRIMARY KEY erstellt implizit einen Index »conversation_visibilities_pkey« für Tabelle »conversation_visibilities«
   -> 0.0667s
-- add_index("conversation_visibilities", ["conversation_id", "person_id"], {:name=>"index_conversation_visibilities_on_conversation_id_and_person_id", :unique=>true})
rake aborted!
Index name 'index_conversation_visibilities_on_conversation_id_and_person_id' on table 'conversation_visibilities' is too long; the limit is 63 characters
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/schema_statements.rb:573:in `add_index_options'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/schema_statements.rb:351:in `add_index'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/activerecord-3.2.13/lib/active_record/migration.rb:466:in `block in method_missing'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `block in say_with_time'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `say_with_time'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/activerecord-3.2.13/lib/active_record/migration.rb:458:in `method_missing'
/var/www/vhosts/example.org/diaspora/db/schema.rb:98:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/activerecord-3.2.13/lib/active_record/schema.rb:50:in `instance_eval'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/activerecord-3.2.13/lib/active_record/schema.rb:50:in `define'
/var/www/vhosts/example.org/diaspora/db/schema.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/activerecord-3.2.13/lib/active_record/railties/databases.rake:402:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/activerecord-3.2.13/lib/active_record/railties/databases.rake:402:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p448@diaspora/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

The interesting part seems to be:

```
Index name 'index_conversation_visibilities_on_conversation_id_and_person_id' on table 'conversation_visibilities' is too long; the limit is 63 characters
```

**Comment by svbergerem** [comment]
PostgreSQL 8.x is not supported anymore: https://en.wikipedia.org/wiki/PostgreSQL#Release_history
