### ISSUE TITLE
OpenGraph incorrectly extracts http:// as URI and fails on that.

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#5206]
I'm surprised URI.extract fails on that.

The reproducing example seems to be something like: `http://…`

```
Workers::GatherOpenGraphData 	

288836, "http:"
	
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http:'

app/models/open_graph_cache.rb:25:in `new'
app/models/open_graph_cache.rb:25:in `fetch_and_save_opengraph_data!'
app/models/open_graph_cache.rb:20:in `find_or_create_by'
app/workers/gather_open_graph_data.rb:12:in `perform'
```

**Comment by jhass** [comment]
Should've been fixed by #5347 and cleaned up by ed0005c44d12e51629481f67164d6fee470841c3
