### ISSUE TITLE
Display an error page when SpoofAttackError is throwed

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5581]
I have this error in my log, I already have it. Looks like the user is using a proxy in his browser.

<pre>Started GET "/" for IP1 at 2015-01-21 11:16:08 +0100
Processing by HomeController#show as HTML
Completed 500 Internal Server Error in 5ms

ActionDispatch::RemoteIp::IpSpoofAttackError (IP spoofing attack?! HTTP_CLIENT_IP="IP2" HTTP_X_FORWARDED_FOR="IP2, IP1"):
  app/controllers/application_controller.rb:84:in `set_locale'
  lib/rack/chrome_frame.rb:39:in `call'
  lib/unicorn_killer.rb:35:in `call'</pre>

We should not be hit by a 500 but display an error message instead.

**Comment by marienfressinaud** [comment]
I can confirm since this error occurred to me. For some non-related reasons, I installed a Firefox addon ([IPFlood](http://ipflood.paulds.fr/)) which change my declared IP at each request.

IP spoofing attack detection is fine but a better error message should be displayed to the user.
