### ISSUE TITLE
Tests not running from bin/rspec or bin/rake spec

### ISSUE THREAD

**Issue by fscz** [diaspora/diaspora#5656]
1
--
```
fscz$ bin/rspec spec/models/profile_spec.rb 
Version: 1.2.0

Usage: spring COMMAND [ARGS]

Commands for spring itself:

  binstub         Generate spring based binstubs. Use --all to generate a binstub for all known commands.
  help            Print available commands.
  status          Show current status.
  stop            Stop all spring processes for this project.

Commands for your application:

  rails           Run a rails command. The following sub commands will use spring: console, runner, generate, destroy.
  rake            Runs the rake command
/Library/Ruby/Gems/2.0.0/gems/bundler-1.7.13/lib/bundler/rubygems_integration.rb:309:in `block in replace_bin_path': undefined method `name' for nil:NilClass (NoMethodError)
	from bin/rspec:7:in `<main>'
```
--

2
--
```
bin/rake spec
Faraday::Builder is now Faraday::RackBuilder.
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/connection_specification.rb:190:in `rescue in spec': Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/connection_specification.rb:187:in `spec'
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_handling.rb:50:in `establish_connection'
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-import-0.6.0/lib/activerecord-import.rb:4:in `establish_connection_with_activerecord_import'
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.1.8/lib/active_record/railtie.rb:129:in `block (2 levels) in <class:Railtie>'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.1.8/lib/active_record/railtie.rb:118:in `block in <class:Railtie>'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `instance_exec'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:180:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/initializable.rb:54:in `run_initializers'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/application.rb:300:in `initialize!'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `public_send'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `method_missing'
	from /Volumes/EXT/Dropbox/devel/diaspora/config/environment.rb:5:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:92:in `preload'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```
--

**Comment by jhass** [comment]
I edited code fences into your post to make it readable at all.

If you have multiple issues, open multiple for them.

About 1, I did not verification work, but this looks like an incompatibility between a recent bundler and spring. I updated spring to the latest version, let's see if that fixed it for you.

About 2, make sure to always set `DB=postgres`, ideally export it in your $SHELLrc or use a tool like autoenv. This is necessary for  now until bundler supports something like https://github.com/bundler/bundler-features/issues/68
