### ISSUE TITLE
Database ecoding is not utf8mb4

### ISSUE THREAD

**Issue by nazar-pc** [diaspora/diaspora#5851]
Update from last stable to 0.5 RC
```
diaspora@diaspora:~/diaspora$ RAILS_ENV=production rake db:migrate
Faraday::Builder is now Faraday::RackBuilder.
Rack::SSL is enabled
== 20150106050733 SetMysqlToUnicodeMb4: migrating =============================
-- remove_index("aspect_visibilities", {:name=>"shareable_and_aspect_id"})
   -> 0.4451s
-- add_index("aspect_visibilities", ["shareable_id", "shareable_type", "aspect_id"], {:name=>"shareable_and_aspect_id", :length=>{"shareable_type"=>189}, :using=>:btree})
   -> 0.0737s
-- remove_index("aspect_visibilities", {:name=>"index_aspect_visibilities_on_shareable_id_and_shareable_type"})
   -> 0.0705s
-- add_index("aspect_visibilities", ["shareable_id", "shareable_type"], {:name=>"index_aspect_visibilities_on_shareable_id_and_shareable_type", :length=>{"shareable_type"=>190}, :using=>:btree})
   -> 0.0749s
-- remove_index("chat_contacts", {:name=>"index_chat_contacts_on_user_id_and_jid"})
   -> 0.0693s
-- add_index("chat_contacts", ["user_id", "jid"], {:name=>"index_chat_contacts_on_user_id_and_jid", :length=>{"jid"=>190}, :using=>:btree, :unique=>true})
   -> 0.0741s
-- remove_index("comments", {:name=>"index_comments_on_guid"})
   -> 0.0734s
-- add_index("comments", ["guid"], {:name=>"index_comments_on_guid", :length=>{"guid"=>191}, :using=>:btree, :unique=>true})
   -> 0.0871s
-- remove_index("likes", {:name=>"index_likes_on_guid"})
   -> 0.0989s
-- add_index("likes", ["guid"], {:name=>"index_likes_on_guid", :length=>{"guid"=>191}, :using=>:btree, :unique=>true})
   -> 0.1094s
-- remove_index("o_embed_caches", {:name=>"index_o_embed_caches_on_url"})
   -> 0.0736s
-- add_index("o_embed_caches", ["url"], {:name=>"index_o_embed_caches_on_url", :length=>{"url"=>191}, :using=>:btree})
   -> 0.0727s
-- remove_index("participations", {:name=>"index_participations_on_guid"})
   -> 0.0748s
-- add_index("participations", ["guid"], {:name=>"index_participations_on_guid", :length=>{"guid"=>191}, :using=>:btree})
   -> 0.1267s
-- remove_index("people", {:name=>"index_people_on_diaspora_handle"})
   -> 0.0727s
-- add_index("people", ["diaspora_handle"], {:name=>"index_people_on_diaspora_handle", :unique=>true, :length=>{"diaspora_handle"=>191}})
   -> 0.0793s
-- remove_index("people", {:name=>"index_people_on_guid"})
   -> 0.0692s
-- add_index("people", ["guid"], {:name=>"index_people_on_guid", :length=>{"guid"=>191}, :using=>:btree, :unique=>true})
   -> 0.0812s
-- remove_index("photos", {:name=>"index_photos_on_status_message_guid"})
   -> 0.0724s
-- add_index("photos", ["status_message_guid"], {:name=>"index_photos_on_status_message_guid", :length=>{"status_message_guid"=>191}, :using=>:btree})
   -> 0.0736s
-- remove_index("posts", {:name=>"index_posts_on_guid"})
   -> 0.1095s
-- add_index("posts", ["guid"], {:name=>"index_posts_on_guid", :length=>{"guid"=>191}, :using=>:btree, :unique=>true})
   -> 0.1283s
-- remove_index("posts", {:name=>"index_posts_on_status_message_guid_and_pending"})
   -> 0.0830s
-- add_index("posts", ["status_message_guid", "pending"], {:name=>"index_posts_on_status_message_guid_and_pending", :length=>{"status_message_guid"=>190}, :using=>:btree})
   -> 0.0913s
-- remove_index("posts", {:name=>"index_posts_on_status_message_guid"})
   -> 0.0762s
-- add_index("posts", ["status_message_guid"], {:name=>"index_posts_on_status_message_guid", :length=>{"status_message_guid"=>191}, :using=>:btree})
   -> 0.0937s
-- remove_index("posts", {:name=>"index_posts_on_author_id_and_root_guid"})
   -> 0.0786s
-- add_index("posts", ["author_id", "root_guid"], {:name=>"index_posts_on_author_id_and_root_guid", :length=>{"root_guid"=>190}, :using=>:btree, :unique=>true})
   -> 0.1042s
-- remove_index("posts", {:name=>"index_posts_on_root_guid"})
   -> 0.1016s
-- add_index("posts", ["root_guid"], {:name=>"index_posts_on_root_guid", :length=>{"root_guid"=>191}})
   -> 0.1015s
-- remove_index("posts", {:name=>"index_posts_on_tweet_id"})
   -> 0.1066s
-- add_index("posts", ["tweet_id"], {:name=>"index_posts_on_tweet_id", :length=>{"tweet_id"=>191}, :using=>:btree})
   -> 0.1042s
-- remove_index("rails_admin_histories", {:name=>"index_rails_admin_histories"})
   -> 0.0749s
-- add_index("rails_admin_histories", ["item", "table", "month", "year"], {:name=>"index_rails_admin_histories", :length=>{"table"=>188}, :using=>:btree})
   -> 0.0791s
-- remove_index("schema_migrations", {:name=>"unique_schema_migrations"})
   -> 0.0828s
-- add_index("schema_migrations", ["version"], {:name=>"unique_schema_migrations", :length=>{"version"=>191}, :using=>:btree})
   -> 0.0755s
-- remove_index("services", {:name=>"index_services_on_type_and_uid"})
   -> 0.0831s
-- add_index("services", ["type", "uid"], {:name=>"index_services_on_type_and_uid", :length=>{"type"=>64, "uid"=>127}, :using=>:btree})
   -> 0.0778s
-- remove_index("taggings", {:name=>"index_taggings_on_taggable_id_and_taggable_type_and_context"})
   -> 0.0867s
-- add_index("taggings", ["taggable_id", "taggable_type", "context"], {:name=>"index_taggings_on_taggable_id_and_taggable_type_and_context", :length=>{"taggable_type"=>95, "context"=>95}, :using=>:btree})
   -> 0.1304s
-- remove_index("tags", {:name=>"index_tags_on_name"})
   -> 0.0770s
-- add_index("tags", ["name"], {:name=>"index_tags_on_name", :length=>{"name"=>191}, :using=>:btree, :unique=>true})
   -> 0.1279s
-- remove_index("users", {:name=>"index_users_on_invitation_service_and_invitation_identifier"})
   -> 0.1159s
-- add_index("users", ["invitation_service", "invitation_identifier"], {:name=>"index_users_on_invitation_service_and_invitation_identifier", :length=>{"invitation_service"=>64, "invitation_identifier"=>127}, :using=>:btree, :unique=>true})
   -> 0.0777s
-- remove_index("users", {:name=>"index_users_on_username"})
   -> 0.0807s
-- add_index("users", ["username"], {:name=>"index_users_on_username", :length=>{"username"=>191}, :using=>:btree, :unique=>true})
   -> 0.0804s
-- remove_index("users", {:name=>"index_users_on_email"})
   -> 0.0733s
-- add_index("users", ["email"], {:name=>"index_users_on_email", :length=>{"email"=>191}, :using=>:btree})
   -> 0.1111s
-- remove_index("notifications", {:name=>"index_notifications_on_target_type_and_target_id"})
   -> 0.0747s
-- add_index("notifications", ["target_type", "target_id"], {:name=>"index_notifications_on_target_type_and_target_id", :length=>{"target_type"=>190}, :using=>:btree})
   -> 0.0832s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Database encoding is not utf8mb4!/home/diaspora/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:17:in `check_config'
/home/diaspora/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:23:in `change_encoding'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:417:in `method_missing'
/home/diaspora/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:8:in `up'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:569:in `up'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/diaspora/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/diaspora/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Database encoding is not utf8mb4!
/home/diaspora/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:17:in `check_config'
/home/diaspora/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:23:in `change_encoding'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:417:in `method_missing'
/home/diaspora/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:8:in `up'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:569:in `up'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/diaspora/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/diaspora/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/diaspora/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

> diaspora@diaspora:~/diaspora$ mysql --version
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.2

**Comment by nazar-pc** [comment]
Config, of course, was updated

**Comment by nazar-pc** [comment]
After commenting:
```
    raise "Database encoding is not #{encoding}!"   if connection_config[:encoding] != encoding
    raise "Database collation is not #{collation}!" if connection_config[:collation] != collation
```
Migrations finished successfully

**Comment by jhass** [comment]
They did? That is there to verify you updated your `database.yml` correctly. Pay attention that the setting is `encoding` not `charset` like it was previously.

**Comment by nazar-pc** [comment]
Yes, they did, here is my config:
```
mysql: &mysql
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "diaspora"
  password: "*****"
  socket: /var/run/mysqld/mysqld.sock
  charset: utf8mb4
  collation: utf8mb4_bin

#postgres: &postgres
  #adapter: postgresql
  #host: localhost
  #port: 5432
  #username: postgres
  #password:
  #encoding: unicode

# Comment the the mysql line and uncomment the postgres line
# if you want to use postgres
common: &common
  # Choose one of the following
  <<: *mysql
  #<<: *postgres

  # Should match environment.sidekiq.concurrency
  #pool: 25

##################################################
#### CONFIGURE ABOVE #############################
##################################################

# Normally you don't need to touch anything here

postgres_travis: &postgres_travis
  adapter: postgresql
  username: postgres
combined: &combined
  <<: *common
development:
  <<: *combined
  database: diaspora_development
production:
  <<: *combined
  database: diaspora_production
test:
  <<: *combined
  database: "diaspora_test"
integration1:
  <<: *combined
  database: diaspora_integration1
integration2:
  <<: *combined
  database: diaspora_integration2
```

I'm not Ruby developer, what encodings that two lines actually compare?

**Comment by jhass** [comment]
````
mysql: &mysql
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "diaspora"
  password: "*****"
  socket: /var/run/mysqld/mysqld.sock
  #######################
  charset: utf8mb4
  ######## Should be ########
  encoding: utf8mb4
  #######################
  collation: utf8mb4_bin

**Comment by nazar-pc** [comment]
Thanks, I missed that small difference
