### ISSUE TITLE
Make diaspora more robust against improper deletion of accounts (Was: Error 500 in Notifications)

### ISSUE THREAD

**Issue by digitalhuman** [diaspora/diaspora#5920]
Hi,

We have a few users who can't see 'all' notifications because they get an error 500. This is because of some checks that are lacking in the NotificationController.
```
Started GET "/notifications" for 212.1*** at 2015-05-04 05:56:52 +0000
Processing by NotificationsController#index as HTML
  Rendered notifications/_notify_popup_item.haml (10.9ms)
  Rendered notifications/_notify_popup_item.haml (3.1ms)
  Rendered notifications/_notify_popup_item.haml (13.2ms)
  Rendered notifications/_notify_popup_item.haml (8.8ms)
  Rendered notifications/_notify_popup_item.haml (6.8ms)
  Rendered notifications/_notify_popup_item.haml (2.4ms)
  Rendered notifications/_notify_popup_item.haml (2.5ms)
  Rendered notifications/_notify_popup_item.haml (2.3ms)
  Rendered notifications/_notify_popup_item.haml (24.8ms)
  Rendered notifications/_notify_popup_item.haml (2.9ms)
  Rendered notifications/_notify_popup_item.haml (9.4ms)
  Rendered notifications/_notify_popup_item.haml (14.1ms)
  Rendered notifications/_notify_popup_item.haml (11.8ms)
  Rendered notifications/_notify_popup_item.haml (8.9ms)
  Rendered notifications/_notify_popup_item.haml (3.7ms)
  Rendered notifications/_notify_popup_item.haml (11.1ms)
  Rendered notifications/_notify_popup_item.haml (2.4ms)
  Rendered notifications/_notify_popup_item.haml (14.2ms)
  Rendered notifications/_notify_popup_item.haml (13.3ms)
  Rendered notifications/_notify_popup_item.haml (9.0ms)
  Rendered notifications/_notify_popup_item.haml (10.3ms)
  Rendered notifications/_notify_popup_item.haml (2.4ms)
  Rendered notifications/_notify_popup_item.haml (2.3ms)
  Rendered notifications/_notify_popup_item.haml (2.3ms)
  Rendered notifications/_notify_popup_item.haml (1.5ms)
Completed 500 Internal Server Error in 471.6ms
```
As you can see. Some notifications are rendered but then an error 500 is generated.

**Comment by jhass** [comment]
I don't think anybody can do anything about this without a way to reproduce.

**Comment by digitalhuman** [comment]
Well this is all it gives me:

Started GET "/notifications" for 212.187.5.4 at 2015-05-04 08:23:45 +0000
Processing by NotificationsController#index as HTML
  Rendered notifications/_notify_popup_item.haml (5.7ms)
  Rendered notifications/_notify_popup_item.haml (2.7ms)
  Rendered notifications/_notify_popup_item.haml (10.9ms)
  Rendered notifications/_notify_popup_item.haml (8.0ms)
  Rendered notifications/_notify_popup_item.haml (6.9ms)
  Rendered notifications/_notify_popup_item.haml (2.5ms)
  Rendered notifications/_notify_popup_item.haml (2.4ms)
  Rendered notifications/_notify_popup_item.haml (3.0ms)
  Rendered notifications/_notify_popup_item.haml (12.2ms)
  Rendered notifications/_notify_popup_item.haml (2.5ms)
  Rendered notifications/_notify_popup_item.haml (9.8ms)
  Rendered notifications/_notify_popup_item.haml (11.2ms)
  Rendered notifications/_notify_popup_item.haml (9.2ms)
  Rendered notifications/_notify_popup_item.haml (7.8ms)
  Rendered notifications/_notify_popup_item.haml (2.6ms)
  Rendered notifications/_notify_popup_item.haml (9.2ms)
  Rendered notifications/_notify_popup_item.haml (2.4ms)
  Rendered notifications/_notify_popup_item.haml (9.7ms)
  Rendered notifications/_notify_popup_item.haml (9.4ms)
  Rendered notifications/_notify_popup_item.haml (7.4ms)
  Rendered notifications/_notify_popup_item.haml (10.3ms)
  Rendered notifications/_notify_popup_item.haml (2.4ms)
  Rendered notifications/_notify_popup_item.haml (2.4ms)
  Rendered notifications/_notify_popup_item.haml (2.3ms)
  Rendered notifications/_notify_popup_item.haml (1.6ms)
Completed 500 Internal Server Error in 361.0ms

ActionView::Template::Error (undefined method `profile' for nil:NilClass):
    1: .notification_element{:data=>{:guid => n.id, :type => (Notification.types.key(n.type) || '')}, :class => (n.unread ? "unread" : "read")}
    2:   .pull-right.unread-toggle
    3:     %i.entypo.eye{ :title => (n.unread ? t('notifications.index.mark_read') : t('notifications.index.mark_unread')) }
    4:   = person_image_tag n.actors.first, :thumb_small
    5:   .notification_message
    6:     = notification_message_for(n)
    7:     %div= timeago(n.created_at)
  app/helpers/people_helper.rb:35:in `person_image_tag'
  app/views/notifications/_notify_popup_item.haml:4:in `_app_views_notifications__notify_popup_item_haml__2900537344476114681_94618280'
  app/controllers/notifications_controller.rb:47:in `block in index'
  app/controllers/notifications_controller.rb:46:in `each'
  app/controllers/notifications_controller.rb:46:in `index'
  lib/rack/chrome_frame.rb:39:in `call'
  lib/unicorn_killer.rb:35:in `call'

**Comment by Flaburgan** [comment]
Did you once manually delete a user account? I had some similar error after deleting a spam account, the users with a notification from that account got a 500.

**Comment by digitalhuman** [comment]
Yes that is what I personally think that is the problem. But now I need a solution :) I deleted some spam accounts back when we started.

**Comment by Flaburgan** [comment]
Well the solution would have been to use the admin panel to delete the account instead of do a `DELETE` directly in the database. Now you have to search in your DB which participations are orphan and edit them.

**Comment by digitalhuman** [comment]
True that should have been the way but shouldn't there be a check in the controller to prevent 500? Because we also had accounts that had error 500 because somebody changed his profile image. Simple basic change but caused an error 500. Personally I think better checking is also part of the solution.

**Comment by jhass** [comment]
"Error 500" is not a specific error, it's the symptom of any *unexpected* error. There's no general way to "just prevent" it.

**Comment by digitalhuman** [comment]
I understand that there is no 'general way', but these 2 issues could been prevented by simple checks.

**Comment by jhass** [comment]
Looking forward to your pull requests adding all these obvious simple checks we miss them!

**Comment by digitalhuman** [comment]
I understand feedback can be hard to handle on a personal level. That's why you should keep it on the professional level. I love to be part of the D* idea and I might idd add these checks.

**Comment by denschub** [comment]
Sure, and closing issues is a great and professional way of handling issues.

**Comment by digitalhuman** [comment]
What would you like to discuss more Dennis?

**Comment by denschub** [comment]
No. This is clearly an issue and somebody will eventually work on it and fix it. You closed the issue, so nobody will see this as an open point. That's why I reopened it.

Feel free to hit the "unsubscribe" button on the right.

**Comment by digitalhuman** [comment]
Yes that is what I wrote. I will add these 2 checks that I talked about. I can't give you any timestamp but since I can solve issues on our server with it it might be soon.

**Comment by goobertron** [comment]
That would be great if you can provide a solution to this issue, thanks!
