### ISSUE TITLE
ActiveModel::MissingAttributeError (can't write unknown attribute `export`)

### ISSUE THREAD

**Issue by Quix0r** [diaspora/diaspora#5980]
This happens with latest master:

````
Started GET "/sidekiq/" for x.x.x.x at 2015-05-22 19:37:06 +0200

ActiveModel::MissingAttributeError (can't write unknown attribute `export`):
  config/routes.rb:16:in `block (2 levels) in <top (required)>'
  lib/rack/chrome_frame.rb:39:in `call'
  lib/unicorn_killer.rb:35:in `call'
````

And another one:
````
Started GET "/admin_panel" for x.x.x.x at 2015-05-22 19:54:06 +0200
Processing by RailsAdmin::MainController#dashboard as HTML
Completed 500 Internal Server Error in 17ms (ActiveRecord: 3.4ms)

ActiveModel::MissingAttributeError (can't write unknown attribute `export`):
  app/controllers/application_controller.rb:84:in `set_locale'
  lib/rack/chrome_frame.rb:39:in `call'
  lib/unicorn_killer.rb:35:in `call'
````

**Comment by jhass** [comment]
This sounds as if your migrations didn't run through

**Comment by Quix0r** [comment]
I followed this, except db:migrate as it empties many important tabkes:

https://wiki.diasporafoundation.org/Updating#Updating_a_production_install

So I use the RVM way. :-)

**Comment by jhass** [comment]
From which version to which version? Migrating the database is not optional and it emptying any table would be a bug.

**Comment by Quix0r** [comment]
I'm not sure, from which version, it must be some months old. Okay, I run first a full backup of my database (diaspora_production).

**Comment by Quix0r** [comment]
````
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Database encoding is not utf8mb4!/var/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:17:in `check_config'
/var/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:23:in `change_encoding'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/activerecord-4.2.1/lib/active_record/migration.rb:417:in `method_missing'
/var/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:8:in `up'
````
It uses utf8_bin on all tables.

**Comment by Quix0r** [comment]
Ah, found it in Changelog. :-)

**Comment by Quix0r** [comment]
Yay, rake is running the ALTER TABLE CONVERT statements ... :dancer: 

I missed to change to "encoding:" i left "charset:" in place ...

**Comment by Quix0r** [comment]
Finally back. :-) Fixed.
