### ISSUE TITLE
NameError: uninitialized constant ActionView::Helpers::ActiveModelHelper after updeate to 0.5.3.0

### ISSUE THREAD

**Issue by raider444** [diaspora/diaspora#6392]
After updating from 0.5.1.0 to 0.5.3.0 I got error:
```
diaspora@np:~/diaspora$ DB=postgres bin/rake db:migrate
rake aborted!
NameError: uninitialized constant ActionView::Helpers::ActiveModelHelper
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/actionview-4.2.4/lib/action_view/helpers.rb:40:in `<module:Helpers>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/actionview-4.2.4/lib/action_view/helpers.rb:4:in `<module:ActionView>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/actionview-4.2.4/lib/action_view/helpers.rb:3:in `<top (required)>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/actionview-4.2.4/lib/action_view/base.rb:5:in `<top (required)>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/actionview-4.2.4/lib/action_view/view_paths.rb:1:in `<top (required)>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/actionpack-4.2.4/lib/abstract_controller/rendering.rb:4:in `<top (required)>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/actionpack-4.2.4/lib/action_controller/base.rb:204:in `<class:Base>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/actionpack-4.2.4/lib/action_controller/base.rb:164:in `<module:ActionController>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/actionpack-4.2.4/lib/action_controller/base.rb:5:in `<top (required)>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/responders-2.1.0/lib/responders/controller_method.rb:37:in `<top (required)>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/responders-2.1.0/lib/responders.rb:15:in `require'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/responders-2.1.0/lib/responders.rb:15:in `<module:Responders>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/responders-2.1.0/lib/responders.rb:9:in `<top (required)>'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
/home/diaspora/diaspora/config/application.rb:4:in `<top (required)>'
/home/diaspora/diaspora/Rakefile:8:in `require'
/home/diaspora/diaspora/Rakefile:8:in `<top (required)>'

ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
Bundler version 1.10.6
rake, version 10.4.2

*** LOCAL GEMS ***

actionmailer (4.2.4, 4.2.2, 4.2.1)
actionpack (4.2.4, 4.2.2, 4.2.1)
actionpack-action_caching (1.1.1)
actionpack-page_caching (1.0.2)
actionview (4.2.4, 4.2.2, 4.2.1)
active_model_serializers (0.9.3)
activejob (4.2.4, 4.2.2, 4.2.1)
activemodel (4.2.4, 4.2.2, 4.2.1)
activerecord (4.2.4, 4.2.2, 4.2.1)
activerecord-import (0.10.0, 0.7.0)
activeresource (4.0.0)
activesupport (4.2.4, 4.2.2, 4.2.1)
acts-as-taggable-on (3.5.0)
acts_as_api (0.4.2)
addressable (2.3.8, 2.3.7)
arel (6.0.3, 6.0.0)
asset_sync (1.1.0)
autoprefixer-rails (5.2.1.1, 5.1.11, 5.1.7.1)
backbone-on-rails (1.2.0.0, 1.1.2.1, 1.1.2.0)
bcrypt (3.1.10)
bigdecimal (1.2.4)
bootstrap-sass (2.3.2.2)
buftok (0.2.0)
builder (3.2.2)
bundler (1.10.6, 1.10.5, 1.9.6, 1.7.6)
bundler-unload (1.0.2)
carrierwave (0.10.0)
celluloid (0.16.0)
celluloid-io (0.16.2)
CFPropertyList (2.3.1)
chunky_png (1.3.4)
coffee-rails (4.1.0)
coffee-script (2.4.1, 2.3.0)
coffee-script-source (1.9.1.1, 1.9.1)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
compass-rails (2.0.4)
configurate (0.3.1, 0.2.0)
connection_pool (2.2.0, 2.1.3)
devise (3.5.1, 3.4.1)
devise-token_authenticatable (0.4.0, 0.3.0)
devise_lastseenable (0.0.6, 0.0.4)
diaspora-vines (0.2.0.develop.1, 0.1.27)
diaspora_federation (0.0.6)
diaspora_federation-rails (0.0.6)
domain_name (0.5.24, 0.5.23)
eco (1.0.0)
eco-source (1.1.0.rc.1)
ejs (1.1.1)
em-hiredis (0.3.0)
entypo-rails (2.2.3, 2.2.2)
equalizer (0.0.11)
erubis (2.7.0)
ethon (0.7.4, 0.7.3)
eventmachine (1.0.8, 1.0.7)
excon (0.45.4, 0.45.3, 0.44.4)
execjs (2.6.0, 2.5.2, 2.4.0)
executable-hooks (1.3.2)
eye (0.7.pre)
facebox-rails (0.2.0)
faraday (0.9.1)
faraday-cookie_jar (0.0.6)
faraday_middleware (0.10.0, 0.9.1)
ffi (1.9.10, 1.9.8)
fission (0.5.0)
fog (1.32.0, 1.30.0, 1.28.0)
fog-atmos (0.1.0)
fog-aws (0.7.3, 0.1.2, 0.1.1)
fog-brightbox (0.8.0, 0.7.1)
fog-core (1.32.0, 1.30.0, 1.29.0)
fog-ecloud (0.1.1, 0.0.2)
fog-google (0.0.7, 0.0.5)
fog-json (1.0.2, 1.0.1, 1.0.0)
fog-local (0.2.1)
fog-powerdns (0.1.1)
fog-profitbricks (0.0.5, 0.0.2)
fog-radosgw (0.0.4, 0.0.3)
fog-riakcs (0.1.0)
fog-sakuracloud (1.0.1, 1.0.0)
fog-serverlove (0.1.2, 0.1.1)
fog-softlayer (0.4.7, 0.4.5, 0.4.1)
fog-storm_on_demand (0.1.1, 0.1.0)
fog-terremark (0.1.0, 0.0.4)
fog-vmfusion (0.1.0, 0.0.1)
fog-voxel (0.1.0, 0.0.2)
fog-xml (0.1.2, 0.1.1)
font-awesome-rails (4.4.0.0, 4.3.0.0)
foreman (0.62.0)
formatador (0.2.5)
gem-wrappers (1.2.7)
globalid (0.3.6, 0.3.5, 0.3.3)
gon (6.0.1, 5.2.3)
haml (4.0.6)
handlebars_assets (0.20.2, 0.20.1)
hashie (3.4.2, 3.4.1, 3.4.0)
hike (1.2.3)
hiredis (0.5.2)
hitimes (1.2.2)
http (0.6.4)
http-cookie (1.0.2)
http_accept_language (2.0.5)
http_parser.rb (0.6.0)
i18n (0.7.0)
i18n-inflector (2.6.7)
i18n-inflector-rails (1.0.7)
ice_cube (0.11.1)
inflecto (0.0.2)
io-console (0.4.2)
ipaddress (0.8.0)
jquery-rails (4.0.4, 3.1.2)
jquery-ui-rails (5.0.5, 5.0.3)
js-routes (1.0.1, 1.0.0)
js_image_paths (0.0.2)
json (1.8.3, 1.8.2, 1.8.1)
json-schema (2.5.1)
jwt (1.5.1, 1.4.1)
kaminari (0.16.3)
kgio (2.9.3)
little-plugger (1.1.3)
logging (2.0.0)
logging-rails (0.5.0)
loofah (2.0.3, 2.0.2, 2.0.1)
macaddr (1.7.1)
mail (2.6.3)
markerb (1.0.2)
memoizable (0.4.2)
messagebus_ruby_api (1.0.3)
mime-types (2.6.1, 2.4.3)
mini_magick (4.2.7, 4.2.3, 4.2.0)
mini_portile (0.6.2)
minitest (5.8.0, 5.7.0, 5.5.1, 4.7.5)
mobile-fu (1.3.1)
multi_json (1.11.2, 1.11.1, 1.11.0)
multi_xml (0.5.5)
multipart-post (2.0.0)
naught (1.0.0)
nested_form (0.3.2)
net-scp (1.2.1)
net-ssh (2.9.2)
nio4r (1.1.1, 1.1.0)
nokogiri (1.6.6.2)
oauth (0.4.7)
oauth2 (1.0.0, 0.9.4)
omniauth (1.2.2)
omniauth-facebook (2.0.1, 1.6.0)
omniauth-oauth (1.1.0, 1.0.1)
omniauth-oauth2 (1.3.1, 1.3.0, 1.1.2)
omniauth-tumblr (1.1)
omniauth-twitter (1.2.0, 1.0.1)
omniauth-wordpress (0.2.2, 0.2.1)
open_graph_reader (0.6.1, 0.5.0)
orm_adapter (0.5.0)
pg (0.18.2, 0.18.1)
psych (2.0.5)
rack (1.6.4, 1.6.2, 1.6.0)
rack-cors (0.4.0, 0.3.1)
rack-google-analytics (1.2.0)
rack-mobile-detect (0.4.0)
rack-piwik (0.3.0)
rack-pjax (0.8.0)
rack-protection (1.5.3)
rack-rewrite (1.5.1)
rack-ssl (1.4.1)
rack-test (0.6.3)
rails (4.2.4, 4.2.2, 4.2.1)
rails-assets-colorbox (1.6.3)
rails-assets-diaspora_jsxc (0.1.4.alpha.1, 0.1.1)
rails-assets-favico.js (0.3.9)
rails-assets-highlightjs (8.6.0, 8.5.0)
rails-assets-jakobmattsson--jquery-elastic (1.6.11)
rails-assets-jeresig--jquery.hotkeys (0.2.0)
rails-assets-jquery (1.11.2, 1.11.1)
rails-assets-jquery-colorbox (1.5.15)
rails-assets-jquery-fullscreen (1.1.4)
rails-assets-jquery-fullscreen-plugin (0.5.0)
rails-assets-jquery-idletimer (1.0.1)
rails-assets-jquery-placeholder (2.1.2, 2.1.1)
rails-assets-jquery-textchange (0.2.3)
rails-assets-jquery-ui (1.10.4)
rails-assets-jquery.slimscroll (1.3.6, 1.3.3)
rails-assets-jquery.ui (1.11.4)
rails-assets-markdown-it (4.4.0, 4.2.1, 4.2.0)
rails-assets-markdown-it--markdown-it-for-inline (0.1.1, 0.1.0)
rails-assets-markdown-it-diaspora-mention (0.3.0)
rails-assets-markdown-it-hashtag (0.3.1, 0.3.0)
rails-assets-markdown-it-sanitizer (0.3.1, 0.3.0)
rails-assets-markdown-it-sub (1.0.0)
rails-assets-markdown-it-sup (1.0.0)
rails-assets-perfect-scrollbar (0.6.4, 0.5.9)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7, 1.0.6)
rails-html-sanitizer (1.0.2)
rails-i18n (4.0.4)
rails-observers (0.1.2)
rails-timeago (2.11.0)
rails_admin (0.7.0, 0.6.7)
railties (4.2.4, 4.2.2, 4.2.1)
raindrops (0.15.0, 0.13.0)
rake (10.4.2, 10.1.0)
rb-fsevent (0.9.5, 0.9.4)
rb-inotify (0.9.5)
rdoc (4.1.0)
redcarpet (3.3.2, 3.2.3)
redis (3.2.1)
redis-namespace (1.5.2, 1.5.1)
remotipart (1.2.1)
request_store (1.2.0, 1.1.0)
responders (2.1.0)
roxml (3.1.6)
ruby-oembed (0.8.14, 0.8.12)
rubygems-bundler (1.4.4)
rubyzip (1.1.7)
rvm (1.11.3.9)
safe_yaml (1.0.4)
sass (3.4.16, 3.4.13)
sass-rails (5.0.1)
sidekiq (3.4.2, 3.3.4, 3.3.3)
sidetiq (0.6.3)
sigar (0.7.3)
simple_captcha2 (0.3.4)
simple_oauth (0.3.1, 0.2.0)
sinatra (1.4.6)
sprockets (2.12.4, 2.12.3)
sprockets-rails (2.3.2, 2.3.1, 2.2.4)
state_machine (1.2.0)
systemu (2.6.5)
test-unit (2.1.5.0)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
timers (4.0.1)
twitter (5.14.0, 4.8.1)
twitter-text (1.12.0, 1.11.0)
typhoeus (0.7.2, 0.7.1)
tzinfo (1.2.2)
uglifier (2.7.2, 2.7.1)
unf (0.1.4)
unf_ext (0.0.7.1, 0.0.6)
unicorn (4.9.0, 4.8.3)
uuid (2.3.8, 2.3.7)
valid (1.0.0)
warden (1.2.3)
will_paginate (3.0.7)
zip-zip (0.3)
```
What did I do wrong?

**Comment by jhass** [comment]
Any output from:

* `git status`
* `git diff``
* `git diff origin/master`
?

**Comment by raider444** [comment]
```
diaspora@np:~/diaspora$ git status
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   Gemfile.lock
#
no changes added to commit (use "git add" and/or "git commit -a")

diaspora@np:~/diaspora$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 3e47fd5..86d12ae 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -433,7 +433,6 @@ GEM
     multi_test (0.1.2)
     multi_xml (0.5.5)
     multipart-post (2.0.0)
-    mysql2 (0.3.18)
     naught (1.0.0)
     nenv (0.2.0)
     nested_form (0.3.2)
@@ -477,6 +476,7 @@ GEM
     orm_adapter (0.5.0)
     parser (2.2.2.6)
       ast (>= 1.1, < 3.0)
+    pg (0.18.2)
     phantomjs (1.9.8.0)
     powerpack (0.1.1)
     pry (0.10.1)
@@ -802,7 +802,6 @@ DEPENDENCIES
   mini_magick (= 4.2.7)
   minitest
   mobile-fu (= 1.3.1)
-  mysql2 (= 0.3.18)
   nokogiri (= 1.6.6.2)
   omniauth (= 1.2.2)
   omniauth-facebook (= 2.0.1)
@@ -810,6 +809,7 @@ DEPENDENCIES
   omniauth-twitter (= 1.2.0)
   omniauth-wordpress (= 0.2.2)
   open_graph_reader (= 0.6.1)
+  pg (= 0.18.2)
   pry
   pry-byebug
   pry-debundle

diaspora@np:~/diaspora$ git diff origin/master
diff --git a/Gemfile.lock b/Gemfile.lock
index 3e47fd5..86d12ae 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -433,7 +433,6 @@ GEM
     multi_test (0.1.2)
     multi_xml (0.5.5)
     multipart-post (2.0.0)
-    mysql2 (0.3.18)
     naught (1.0.0)
     nenv (0.2.0)
     nested_form (0.3.2)
@@ -477,6 +476,7 @@ GEM
     orm_adapter (0.5.0)
     parser (2.2.2.6)
       ast (>= 1.1, < 3.0)
+    pg (0.18.2)
     phantomjs (1.9.8.0)
     powerpack (0.1.1)
     pry (0.10.1)
@@ -802,7 +802,6 @@ DEPENDENCIES
   mini_magick (= 4.2.7)
   minitest
   mobile-fu (= 1.3.1)
-  mysql2 (= 0.3.18)
   nokogiri (= 1.6.6.2)
   omniauth (= 1.2.2)
   omniauth-facebook (= 2.0.1)
@@ -810,6 +809,7 @@ DEPENDENCIES
   omniauth-twitter (= 1.2.0)
   omniauth-wordpress (= 0.2.2)
   open_graph_reader (= 0.6.1)
+  pg (= 0.18.2)
   pry
   pry-byebug
   pry-debundle
```

**Comment by jhass** [comment]
We're not sure where the error came from but could resolve it by updating RVM to its master version and installing Ruby 2.1.7.
