### ISSUE TITLE
500 error in rails_admin when creating a new user

### ISSUE THREAD

**Issue by axilleas** [diaspora/diaspora#6413]
For starters I'm on 5.3, haven't tested the develop branch.

Visit `admin_panel/user/new`

```
[2015-09-20T00:12:16] INFO  PID-10706 TID-6889100 ActionController::Base: Processing by RailsAdmin::MainController#new as HTML
[2015-09-20T00:12:16] INFO  PID-10706 TID-6889100 ActionController::Base: Parameters: {"model_name"=>"user"}
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.9ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_text.html.haml (0.9ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_boolean.html.haml (0.8ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_boolean.html.haml (0.7ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.5ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.5ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.6ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.5ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.5ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_datetime.html.haml (3.8ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_datetime.html.haml (3.6ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.6ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_datetime.html.haml (3.7ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_datetime.html.haml (3.8ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.6ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.6ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.5ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.5ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_field.html.haml (0.5ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/_form_filtering_select.html.haml (14.4ms)
  Rendered vendor/bundle/ruby/gems/rails_admin-0.7.0/app/views/rails_admin/main/new.html.haml within layouts/rails_admin/application (80.4ms)
[2015-09-20T00:12:16] INFO  PID-10706 TID-6889100 ActionController::Base: Completed 500 Internal Server Error in 110ms (ActiveRecord: 2.3ms)
[2015-09-20T00:12:16] FATAL PID-10706 TID-6889100 Rails: 
ActionView::Template::Error (User#name delegated to person.name, but person is nil: #<User id: nil,
 username: nil, serialized_private_key: nil, getting_started: true, disable_mail: false, language: 
nil, email: "", encrypted_password: "", invitation_token: nil, invitation_sent_at: nil, reset_passw
ord_token: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_a
t: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: nil, updated_at: nil, invitation
_service: nil, invitation_identifier: nil, invitation_limit: nil, invited_by_id: nil, invited_by_ty
pe: nil, authentication_token: nil, unconfirmed_email: nil, confirm_email_token: nil, locked_at: ni
l, show_community_spotlight_in_stream: true, auto_follow_back: false, auto_follow_back_aspect_id: n
il, hidden_shareables: {}, reset_password_sent_at: nil, last_seen: nil, remove_after: nil, export: 
nil, exported_at: nil, exporting: false, strip_exif: true, exported_photos_file: nil, exported_phot
os_at: nil, exporting_photos: false>):
    31: - if authorized?(:new, config.abstract_model) && field.inline_add
    32:   - path_hash = { model_name: config.abstract_model.to_param, modal: true }
    33:   - path_hash.merge!({ associations: { field.inverse_of => (form.object.persisted? [3/1848]
bject.id : 'new') } }) if field.inverse_of
    34:   = link_to "<i class=\"icon-plus icon-white\"></i> ".html_safe + wording_for(:link, :new, 
config.abstract_model), '#', data: { link: new_path(path_hash) }, class: "btn btn-info create", sty
le: 'margin-left:10px'
    35: 
    36: - if edit_url.present? && field.inline_edit
    37:   = link_to "<i class=\"icon-pencil icon-white\"></i> ".html_safe + wording_for(:link, :edi
t, config.abstract_model), '#', data: { link: edit_url }, class: "btn btn-info update #{field.value
.nil? && 'disabled'}", style: 'margin-left:10px'
  app/models/user.rb:43:in `rescue in name'
  app/models/user.rb:43:in `name'
  lib/rack/chrome_frame.rb:39:in `call'
  lib/unicorn_killer.rb:35:in `call'
```
##

**Comment by jhass** [comment]
You shouldn't, we should blacklist those routes in the RailsAdmin config.

**Comment by axilleas** [comment]
That makes sense now.

**Comment by deXterbed** [comment]
@jhass do you mean all the routes(for all the models) or just for the user?

**Comment by jhass** [comment]
@deXterbed From my mind, all but `Role` shouldn't be creatable via rails_admin.

**Comment by jaywink** [comment]
:+1: for my blacklisting the whole admin.
