### ISSUE TITLE
Rake abort when running db migration from develop mid april to current develop

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#6827]
```
bin/rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
Rack::SSL is enabled
rake aborted!
ArgumentError: wrong number of arguments (1 for 0)
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/diaspora-prosody-config-0.0.4/lib/diaspora-prosody-config.rb:33:in `update_configuration'
/home/diaspora/diaspora/config/initializers/prosody.rb:5:in `<top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:166:in `instrument'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:651:in `load_config_initializer'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:615:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:44:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:413:in `call'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
/home/diaspora/diaspora/config/environment.rb:5:in `<top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:328:in `require_environment!'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/diaspora/.rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
bin/rake:9:in `<main>'
Tasks: TOP => db:migrate => environment
```

**Comment by denschub** [comment]
Possible regression of #6779, /cc @Zauberstuhl

**Comment by Zauberstuhl** [comment]
@Flaburgan can you reproduce it? and if so how did you do it?

Something like this works for me without errors (the commit is from Apr 13, 2016):

```
$ git checkout b0e608aa38a9997c63b8ce067e892c4de0cff438
$ bundle install
$ rvm list
=> ruby-2.2.1 [ x86_64 ]
$ bundle exec rake db:drop db:create db:schema:load db:migrate
$ git pull origin develop
$ bundle exec rake db:migrate
```

**Comment by Flaburgan** [comment]
I just tried locally and get the same problem, with postgresql database:
```
git pull upstream develop
bin/bundle -> Installing diaspora-prosody-config 0.0.4
bin/rake db:migrate ->
/home/fla/.rvm/gems/ruby-2.2.1@diaspora/gems/diaspora-prosody-config-0.0.4/lib/diaspora-prosody-config.rb:33:in `update_configuration': wrong number of arguments (1 for 0) (ArgumentError)
```

The migration went fine when run on your specific commit, but the crash is still there back to the develop branch.

**Comment by Zauberstuhl** [comment]
oh thats embarrassing .. someone forgot to bump the latest version.
Please run `bundle update diaspora-prosody-config` that should install v0.0.5 and fix your problem.

**Comment by Flaburgan** [comment]
I confirm the bump fixes the problem.
