### ISSUE TITLE
500 when commenting on a reshare of a deleted post

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#7206]
```
NoMethodError (undefined method `author_name' for nil:NilClass):
  app/models/reshare.rb:65:in `comment_email_subject'
  app/models/comment.rb:24:in `comment_email_subject'
  app/mailers/notification_mailers/comment_on_post.rb:11:in `set_headers'
  app/mailers/notification_mailers/base.rb:19:in `block in initialize'
  app/mailers/notification_mailers/base.rb:48:in `with_recipient_locale'
  app/mailers/notification_mailers/base.rb:18:in `initialize'
  app/mailers/notifier.rb:96:in `new'
  app/mailers/notifier.rb:96:in `send_notification'
  app/mailers/notifier.rb:75:in `comment_on_post'
  app/workers/mail/comment_on_post.rb:7:in `perform'
  app/models/user.rb:338:in `mail'
  app/models/notification.rb:16:in `email_the_user'
  app/models/notifications/comment_on_post.rb:21:in `notify'
  app/services/notification_service.rb:13:in `block in notify'
  app/services/notification_service.rb:13:in `each'
  app/services/notification_service.rb:13:in `notify'
  app/workers/receive_local.rb:10:in `perform'
  lib/diaspora/federation/dispatcher.rb:48:in `deliver_to_local'
  lib/diaspora/federation/dispatcher.rb:41:in `deliver_to_subscribers'
  lib/diaspora/federation/dispatcher.rb:27:in `dispatch'
  app/workers/deferred_dispatch.rb:14:in `perform'
  lib/diaspora/federation/dispatcher.rb:22:in `defer_dispatch'
  lib/diaspora/federated/generator.rb:15:in `create!'
  app/models/user/social_actions.rb:3:in `comment!'
  app/services/comment_service.rb:8:in `create'
  app/controllers/comments_controller.rb:15:in `create'
  lib/rack/internet_explorer_version.rb:34:in `call'
```

**Comment by niharika88** [comment]
I want to work on it?

**Comment by svbergerem** [comment]
Ok?
