### ISSUE TITLE
500 in a user atom feed

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7249]
```
[2016-12-13T10:17:05] INFO  PID-11028 TID-8215938281780 Rails: Started GET "/public/fla.atom" for x.x.x.x at 2016-12-13 10:17:05 +0100
[2016-12-13T10:17:05] INFO  PID-11028 TID-8215938281780 ActionController::Base: Processing by UsersController#public as ATOM
[2016-12-13T10:17:05] INFO  PID-11028 TID-8215938281780 ActionController::Base:   Parameters: {"username"=>"fla"}
  Rendered users/public.atom.builder (16.0ms)
[2016-12-13T10:17:05] INFO  PID-11028 TID-8215938281780 ActionController::Base: Completed 500 Internal Server Error in 61ms (ActiveRecord: 22.8ms)
[2016-12-13T10:17:05] FATAL PID-11028 TID-8215938281780 Rails: 
ActionView::Template::Error (undefined method `lstrip' for nil:NilClass):
    30:     feed.entry post, :url => "#{@user.url}p/#{post.id}",
    31:       :id => "#{@user.url}p/#{post.id}" do |entry|
    32: 
    33:       entry.title post.message.title
    34:       entry.content post.message.markdownified(disable_hovercards: true), :type => 'html'
    35:       entry.tag! 'activity:verb', 'http://activitystrea.ms/schema/1.0/post'
    36:       entry.tag! 'activity:object-type', 'http://activitystrea.ms/schema/1.0/note'
  lib/diaspora/message_renderer.rb:214:in `title'
  app/views/users/public.atom.builder:33:in `block (3 levels) in _app_views_users_public_atom_builder__3305162908281538328_8216011566200'
  app/views/users/public.atom.builder:30:in `block (2 levels) in _app_views_users_public_atom_builder__3305162908281538328_8216011566200'
  app/views/users/public.atom.builder:29:in `each'
  app/views/users/public.atom.builder:29:in `block in _app_views_users_public_atom_builder__3305162908281538328_8216011566200'
  app/views/users/public.atom.builder:1:in `_app_views_users_public_atom_builder__3305162908281538328_8216011566200'
  lib/rack/internet_explorer_version.rb:34:in `call'
```

d-fr is running last develop. I tried an other user on d-fr and it worked, so I guess a specific post is faulty here.

**Comment by Flaburgan** [comment]
The post causing the problem is [this one](https://diaspora-fr.org/posts/35247cc0a2750134f0462a0000053625). I tried with an empty account, the feed was displayed properly then I reshared this post and now I reproduce the 500.

Notice that the feed of the original author doesn't crash so it's only the reshare which is problematic.
@SuperTux88 said it's because the post contains no text, only an image.

**Comment by Flaburgan** [comment]
Hm, I don't think the code changed but I don't reproduce this locally, posting an empty message with only an image, the atom feed is still fine (even if the title is empty in it, of course). Same when I reshare this post and check the atom feed with the reshare in it.
