### ISSUE TITLE
Redis server crash after server restart

### ISSUE THREAD

**Issue by Kakise** [diaspora/diaspora#7296]
Hello,
Since the update to the latest minor version for my pod, the redis server crashes after every server restart. I need to manually start it (and when I manually start it, it reinitialize every stats). I didn't have this error while on 6.2.0.
Any help?

**Comment by goobertron** [comment]
Try IRC for support like this. If it turns out to be a bug in the Diaspora software, then a Github ticket will be merited.

IRC link: https://webchat.freenode.net/?channels=diaspora

**Comment by Flaburgan** [comment]
Can you please provide the log information: the output in the console, the content of `log/production.log` and `log/sidekiq.log` when you're executing `script/server`?

**Comment by Kakise** [comment]
I don't use `script/server` I start diaspora using Passenger & Nginx and then start sidekiq using a systemd service. It was working perfectly until latest update.

sidekiq.log:
```# Logfile created on 2016-12-22 11:05:38 -0500 by logger.rb/56438
2016-12-22T16:05:58.176Z 20858 TID-8j6qg INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T16:45:16.302Z 3470 TID-4dxw8 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T16:46:34.939Z 3938 TID-5emz4 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T16:47:13.683Z 4283 TID-76764 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T16:48:14.621Z 4717 TID-5af9g INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T16:49:35.666Z 5261 TID-ab3kg INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T16:52:54.540Z 6431 TID-bnqh8 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T16:54:39.601Z 7565 TID-972e8 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T16:55:59.176Z 7853 TID-7mj0w INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T16:57:33.404Z 8378 TID-5tk9c INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:00:37.012Z 9275 TID-am5sk INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:02:34.956Z 9935 TID-2fj68 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:03:15.234Z 10283 TID-6ccm8 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:03:58.025Z 10664 TID-bcukw INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:06:12.000Z 11212 TID-bjvf4 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:06:36.209Z 11381 TID-4h3oc INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:07:04.320Z 11519 TID-9tpso INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:09:28.323Z 12111 TID-8w064 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:10:07.562Z 12292 TID-76dhw INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:19:01.135Z 14529 TID-1yuog INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:19:29.869Z 14716 TID-bqdb4 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:20:03.359Z 14854 TID-9z5r4 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:20:25.399Z 14960 TID-5hg48 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:21:24.905Z 15228 TID-3cpuk INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T17:26:50.775Z 16935 TID-590pg INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T18:59:56.630Z 8883 TID-bhxwc INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T19:02:25.617Z 9954 TID-6gqmk INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T19:05:56.087Z 10879 TID-a374g INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2016-12-22T19:07:58.157Z 11487 TID-5fowo INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
uninitialized constant TurboDevAssets
/home/diaspora/diaspora/config/environments/development.rb:42:in `block in <top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `instance_eval'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `configure'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:182:in `configure'
/home/diaspora/diaspora/config/environments/development.rb:1:in `<top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/2.1.0/tsort.rb:411:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
/home/diaspora/diaspora/config/environment.rb:5:in `<top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.2.2/lib/sidekiq/cli.rb:239:in `boot_system'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.2.2/lib/sidekiq/cli.rb:50:in `run'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.2.2/bin/sidekiq:12:in `<top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/bin/sidekiq:23:in `load'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/bin/sidekiq:23:in `<main>'
2016-12-28T10:56:19.404Z 26252 TID-25jao INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
Rack::SSL is enabled
2016-12-28T10:58:42.676Z 27149 TID-6uz18 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
uninitialized constant TurboDevAssets
/home/diaspora/diaspora/config/environments/development.rb:42:in `block in <top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `instance_eval'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `configure'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:182:in `configure'
/home/diaspora/diaspora/config/environments/development.rb:1:in `<top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/2.1.0/tsort.rb:411:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
/home/diaspora/diaspora/config/environment.rb:5:in `<top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.2.2/lib/sidekiq/cli.rb:239:in `boot_system'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.2.2/lib/sidekiq/cli.rb:50:in `run'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.2.2/bin/sidekiq:12:in `<top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/bin/sidekiq:23:in `load'
/home/diaspora/diaspora/vendor/bundle/ruby/2.1.0/bin/sidekiq:23:in `<main>'
2017-01-07T16:08:59.310Z 2383 TID-a72lk INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2017-01-07T16:13:26.702Z 3267 TID-39qt8 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
Rack::SSL is enabled
WARNING: You are running Diaspora in production without Sidekiq
         workers turned on.  Please set single_process_mode to false in
         config/diaspora.yml.
2017-01-08T12:58:35.839Z 21884 TID-8x2i4 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2017-01-08T13:10:39.012Z 23406 TID-2m7rw INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2017-01-08T13:28:22.414Z 25641 TID-2r4s4 INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2017-01-08T17:48:07.456Z 15526 TID-a8tto INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2017-01-26T17:53:56.470Z 12881 TID-7oang INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2017-01-26T17:56:03.721Z 13110 TID-3gkwo INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2017-01-26T17:57:21.552Z 13178 TID-41nuc INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
2017-01-26T21:29:11.333Z 1429 TID-2ohys INFO: Booting Sidekiq 4.2.2 with redis options {:url=>nil}
```

**Comment by svbergerem** [comment]
@Kakise What is the status here? Are you still experiencing the problems? `uninitialized constant TurboDevAssets` sounds like you are running the server in development mode.

**Comment by Kakise** [comment]
I close this issue as the problem was in my hosting provider side's.
