### ISSUE TITLE
Posting to tumblr fails due to Type error

### ISSUE THREAD

**Issue by oliof** [diaspora/diaspora#7313]
Trying diaspora integration for tumblr, I can successfully setup the API endpoint and connect my account, but posting fails. The diaspora production.log tells me it encounters a Type error:

```
[2017-02-08T11:03:32] WARN  PID-17173 TID-83148480 Sidekiq: {"class":"Workers::PostToService","args":[3,692,"https://pod.mausdompteur.de//p/11179570d01c0134e4f05
e2b4406900e"],"retry":10,"queue":"medium","backtrace":15,"jid":"1a14ced5aa989717491cf238","created_at":1486551775.5640457,"locale":"en","enqueued_at":1486551811.
8911495,"error_message":"no implicit conversion of String into Integer","error_class":"TypeError","failed_at":1486551776.148547,"retry_count":1,"error_backtrace"
:["app/models/services/tumblr.rb:19:in `[]'","app/models/services/tumblr.rb:19:in `post'","app/workers/post_to_service.rb:12:in `perform'"],"retried_at":14865518
12.1355677}
[2017-02-08T11:03:32] WARN  PID-17173 TID-83148480 Sidekiq: TypeError: no implicit conversion of String into Integer
[2017-02-08T11:03:32] WARN  PID-17173 TID-83148480 Sidekiq: app/models/services/tumblr.rb:19:in `[]'
app/models/services/tumblr.rb:19:in `post'
app/workers/post_to_service.rb:12:in `perform'
[2017-02-08T11:04:10] INFO  PID-17173 TID-23305200 Sidekiq: Workers::PostToService JID-1a14ced5aa989717491cf238: start
[2017-02-08T11:04:11] INFO  PID-17173 TID-23305200 Sidekiq: Workers::PostToService JID-1a14ced5aa989717491cf238: fail: 0.277 sec
[2017-02-08T11:04:11] WARN  PID-17173 TID-23305200 Sidekiq: {"class":"Workers::PostToService","args":[3,692,"https://pod.mausdompteur.de//p/11179570d01c0134e4f05
e2b4406900e"],"retry":10,"queue":"medium","backtrace":15,"jid":"1a14ced5aa989717491cf238","created_at":1486551775.5640457,"locale":"en","enqueued_at":1486551850.
8104918,"error_message":"no implicit conversion of String into Integer","error_class":"TypeError","failed_at":1486551776.148547,"retry_count":2,"error_backtrace"
:["app/models/services/tumblr.rb:19:in `[]'","app/models/services/tumblr.rb:19:in `post'","app/workers/post_to_service.rb:12:in `perform'"],"retried_at":14865518
51.087682}
[2017-02-08T11:04:11] WARN  PID-17173 TID-23305200 Sidekiq: TypeError: no implicit conversion of String into Integer
[2017-02-08T11:04:11] WARN  PID-17173 TID-23305200 Sidekiq: app/models/services/tumblr.rb:19:in `[]'
app/models/services/tumblr.rb:19:in `post'
app/workers/post_to_service.rb:12:in `perform'
```

**Comment by oliof** [comment]
This is with  diaspora 0.6.3.0-p1702cc1c

**Comment by oliof** [comment]
And, as is wont, the error goes away with the filing of the bug. Closing for now.
