### ISSUE TITLE
NoMethodError when sending a Welcome Message if the admin account is not found

### ISSUE THREAD

**Issue by hfroese** [diaspora/diaspora#7363]
Enabling welcome message causes error 500 to new registered user.
Not getting_started page but error 500.

**Comment by Flaburgan** [comment]
Please check the `production.log` and post the stacktrace here.

**Comment by hfroese** [comment]
OK - here we go:

```
[2017-03-13T17:36:00] INFO  PID-3056 TID-12996840 Rails: Started POST "/users" for 84.141.162.14 at 2017-03-13 17:36:00 +0100
[2017-03-13T17:36:00] INFO  PID-3056 TID-12996840 ActionController::Base: Processing by RegistrationsController#create as HTML
[2017-03-13T17:36:00] INFO  PID-3056 TID-12996840 ActionController::Base:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"tt8aLmO/dDht8R2ZpCwkJezYINEtBXAcyVMTSA9Y/TtKMDpIHx4s9R1n6p4rJGnmduXFJPpSVNdNfe24WNFZLA==", "user"=>{"email"=>"testaccount@diaspora.zone", "username"=>"testaccount", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Konto erstellen"}
[2017-03-13T17:36:02] INFO  PID-3020 TID-97685100 Sidekiq: Workers::DeferredDispatch JID-b1efbd4a8621c570d7884e89: start
[2017-03-13T17:36:02] INFO  PID-3056 TID-12996840 ActionController::Base: Completed 500 Internal Server Error in 1708ms (ActiveRecord: 51.2ms)
[2017-03-13T17:36:02] FATAL PID-3056 TID-12996840 Rails: 
NoMethodError (undefined method `person' for nil:NilClass):
  app/models/user.rb:435:in `send_welcome_message'
  app/controllers/registrations_controller.rb:17:in `create'
  lib/rack/internet_explorer_version.rb:34:in `call'
```

**Comment by denschub** [comment]
You don't have an admin account set up, which is why there is no sender for the welcome message. [Please promote an account](https://wiki.diasporafoundation.org/FAQ_for_pod_maintainers#What_are_roles_and_how_do_I_use_them.3F_.2F_Make_yourself_an_admin_or_assign_moderators) to the admin role and the error will be gone.

**Comment by SuperTux88** [comment]
You need to set the admin here for the welcome message: https://github.com/diaspora/diaspora/blob/master/config/diaspora.yml.example#L682

**Comment by denschub** [comment]
Oh! Yeah!

**Comment by SuperTux88** [comment]
We already check if you set an admin there, so you probably set an invalid user that now isn't found.

**Comment by hfroese** [comment]
@SuperTux88 
That's it! 
I had of course an admin account but I'm running pods since... and I'd ever added the full ID %-)
Everything is working now. 
Thx guys

**Comment by denschub** [comment]
Reopening. This is something we can easily solve by returning early...

**Comment by hfroese** [comment]
I have another welcome message related question:
What is the maximum length of the welcome message and how to format it - line break etc. - is Markdown allowed?

**Comment by SuperTux88** [comment]
It is a normal message, like every other message you write. So with markdown and I think 65535 chars long.

**Comment by hfroese** [comment]
thx @SuperTux88  - I'll test it.
