### ISSUE TITLE
There was an error in your Gemfile, and Bundler cannot continue...

### ISSUE THREAD

**Issue by jadeye** [diaspora/diaspora#7417]
This is my first try at [`diaspora`](https://wiki.diasporafoundation.org/Installation/Heroku)....**Error**:

```
$ bundle --without development test heroku production assets
/home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dependency.rb:42:in `block in initialize': undefined method `to_sym' for {:optional=>true}:Hash (NoMethodError)
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dependency.rb:42:in `map'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dependency.rb:42:in `initialize'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:76:in `new'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:76:in `gem'
       /media/Venus/diaspora/Gemfile:64:in `block in eval_gemfile'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:164:in `group'
       /media/Venus/diaspora/Gemfile:63:in `eval_gemfile'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:30:in `instance_eval'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:30:in `eval_gemfile'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:9:in `evaluate'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/definition.rb:26:in `build'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler.rb:152:in `definition'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/cli.rb:253:in `install'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/vendor/thor/command.rb:27:in `run'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/vendor/thor.rb:363:in `dispatch'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/vendor/thor/base.rb:440:in `start'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/cli.rb:10:in `start'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/bin/bundle:20:in `block in <top (required)>'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/bin/bundle:20:in `<top (required)>'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/bin/bundle:23:in `load'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/bin/bundle:23:in `<main>'
       /home/jadeye/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
       /home/jadeye/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
There was an error in your Gemfile, and Bundler cannot continue.
```
Tried all the above but in vain...
Also read all related to `locale`, regenerated `locale`,
Tried most of the suggested [here](http://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue) with no luck...
`Bundler version 1.5.3`
`Ubuntu 14.04.5`

Any ides anyone...??

P.s. couldn't find `Edit Gemfile and change ENV['DB'] ||= 'mysql' to ENV['DB'] ||= 'postgres'.` - does it no longer exist??

**Comment by goobertron** [comment]
Hi, Github is for bug reports and development issues in the core code base, not for help with installations/setup.

Please try the [podmin support channel](https://discourse.diasporafoundation.org/c/support/podmin-support) in our new Discourse instance, or our [IRC channel](https://wiki.diasporafoundation.org/How_we_communicate#IRC). There you should get the help you need.

**Comment by jhass** [comment]
Bundler 1.5.3 is ancient and not supported by diaspora, please update to a later version.

As already mentioned please use IRC or Discourse for further questions, thanks!
