### ISSUE TITLE
"migrations:run_account_deletions" fails

### ISSUE THREAD

**Issue by jonsger** [diaspora/diaspora#7650]
Hi,

I updated my pod recently to the actual [dev-branch](https://github.com/diaspora/diaspora/commit/42a81290163f559a54db9d8193afdcbeba834269). After some struggles with rvm and bundler I get my pod (jons.gr) finally updated. But when I now run `RAILS_ENV=production bin/rake migrations:run_account_deletions` as advised, I getting this error message:

```diaspora@ubuntuserver:~/diaspora$ RAILS_ENV=production bin/rake --trace migrations:run_account_deletions 
** Invoke migrations:run_account_deletions (first_time)
** Invoke environment (first_time)
** Execute environment
Rack::SSL is enabled
** Execute migrations:run_account_deletions
Running account deletions...
Deleting armin@jons.gr ...rake aborted!
NoMethodError: undefined method `contact_people' for nil:NilClass
/home/diaspora/diaspora/app/models/account_deletion.rb:27:in `subscribers'
/home/diaspora/diaspora/lib/diaspora/federation/dispatcher.rb:81:in `subscribers'
/home/diaspora/diaspora/lib/diaspora/federation/dispatcher.rb:51:in `deliver_to_subscribers'
/home/diaspora/diaspora/lib/diaspora/federation/dispatcher.rb:29:in `dispatch'
/home/diaspora/diaspora/app/models/account_deletion.rb:22:in `perform!'
/home/diaspora/diaspora/lib/tasks/migrations.rake:75:in `block (3 levels) in <top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `block (2 levels) in find_each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `block in find_each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:129:in `block in find_in_batches'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:230:in `block in in_batches'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:214:in `loop'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:214:in `in_batches'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:128:in `find_in_batches'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:62:in `find_each'
/home/diaspora/diaspora/lib/tasks/migrations.rake:67:in `block (2 levels) in <top (required)>'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/home/diaspora/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:81:in `block in run'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
bin/rake:9:in `<main>'
Tasks: TOP => migrations:run_account_deletions
```

My setup:
OS: Ubuntu 16.04.3 LTS
Ruby-Version: 2.4.1p111
DB: mysql  Ver 15.1 Distrib 10.0.31-MariaDB
Diaspora: 42a81290163f559a54db9d8193afdcbeba834269

If you need any further information regarding my setup or for reproducing this bug, please let me know.

Jonathan

**Comment by SuperTux88** [comment]
It looks like you modified your database by hand, because otherwise this could never happen. You have an `account_deletion` in your database but the `user` for this person doesn't exist anymore (but it should, because it is a user from your pod, so you should have the `user` in your database). So you probably deleted that user manually from the database.

Since you modified your database I don't know in which state it is and what else is invalid, but you need to either mark the `account_deletion` as completed or just delete it, then the `RAILS_ENV=production bin/rake migrations:run_account_deletions` should work.
