### ISSUE TITLE
Error 500 when posting an invalid `diaspora://` link

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7651]
I tried to post the following comment:
```
`diaspora://diaspora_news@diaspora-fr.org/posts/047824b0999a0135f9a631f93c8c141d` donne 
diaspora://diaspora_news@diaspora-fr.org/posts/047824b0999a0135f9a631f93c8c141d (normalement vous voyez le lien de votre pod) et non pas https://diaspora-fr.org/posts/3094290 (le lien de mon pod).
```
on the post itself (so referencing a post in one of its comments) https://diaspora-fr.org/posts/3094290 and I got a 500:

```
[2017-10-25T17:04:53] INFO  PID-2247 TID-7994320 Rails: Started POST "/posts/3094290/comments" for X.X.X.X at 2017-10-25 17:04:53 +0200
[2017-10-25T17:04:53] INFO  PID-2247 TID-7994320 ActionController::Base: Processing by CommentsController#create as JSON
[2017-10-25T17:04:53] INFO  PID-2247 TID-7994320 ActionController::Base:   Parameters: {"text"=>"[FILTERED]", "post_id"=>"3094290", "comment"=>{"text"=>"[FILTERED]"}}
[2017-10-25T17:04:53] INFO  PID-2247 TID-7994320 ActionController::Base: Completed 500 Internal Server Error in 47ms (ActiveRecord: 20.1ms)
[2017-10-25T17:04:53] FATAL PID-2247 TID-7994320 Rails:   
[2017-10-25T17:04:53] FATAL PID-2247 TID-7994320 Rails: DiasporaFederation::Entity::UnknownEntity ('Posts' not found):
[2017-10-25T17:04:53] FATAL PID-2247 TID-7994320 Rails:   
[2017-10-25T17:04:53] FATAL PID-2247 TID-7994320 Rails: app/models/reference.rb:18:in `block in create_references'
app/models/reference.rb:17:in `each'
app/models/reference.rb:17:in `create_references'
lib/diaspora/federated/generator.rb:15:in `create!'
app/models/user/social_actions.rb:5:in `comment!'
app/services/comment_service.rb:10:in `create'
app/controllers/comments_controller.rb:22:in `create'

**Comment by SuperTux88** [comment]
First: `diaspora://` links are not supported yet from many pods, so it's not recommended to use them yet. When they are supported from enough pods they will be created automatically from the frontend when you add a pod-local link (this functionality will be added in a future release).

Second: Your link is invalid, that's why it fails. It should be `diaspora://diaspora_news@diaspora-fr.org/post/047824b0999a0135f9a631f93c8c141d`. This wouldn't be a problem when it would be automatically generated from the frontend.

**Comment by Flaburgan** [comment]
Hm, I get your point, but I still feel like diaspora* should return an error message saying "posts" entity is unknown instead of a 500, don't you think so?

**Comment by SuperTux88** [comment]
No, because users shouldn't create these links by hand. And a users wouldn't understand such error message. And adding a validation to return a special error message for a special case which should never happen would only add complexity at a place where it shouldn't be.

**Comment by Flaburgan** [comment]
Fair enough.

**Comment by svbergerem** [comment]
Shouldn't we just ignore invalid URLs? I'm even unable to submit the following text as a comment:

```
Try this: `diaspora://unknown@localhost:3000/post/thislookslikeavalidguid123456789`
```

**Comment by SuperTux88** [comment]
Yes, you're right, we should ignore errors/invalid urls.
