### ISSUE TITLE
Cannot start diaspora*: Exception: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by dest4** [diaspora/diaspora#7674]
After a soft reboot, I could not start Diaspora* 7.1.1 again.
Debugging info below. Help would be appreciated.

```
$ ./script/server 
Starting Diaspora in production mode with 1 Sidekiq worker(s).

I, [2017-12-14T19:08:43.843362 #17369]  INFO -- : [diaspora:__default__] call: 
I, [2017-12-14T19:08:43.843703 #17369]  INFO -- : [diaspora:__default__] schedule :monitor (load by user)
I, [2017-12-14T19:08:43.844298 #17369]  INFO -- : [diaspora:__default__] => monitor  (load by user)
I, [2017-12-14T19:08:43.844652 #17369]  INFO -- : [diaspora:__default__] starting async with 0.2s chain monitor 
I, [2017-12-14T19:08:43.845056 #17369]  INFO -- : [diaspora:sidekiq] call: 
I, [2017-12-14T19:08:43.845902 #17369]  INFO -- : [diaspora:sidekiq] schedule :monitor (load by user)
I, [2017-12-14T19:08:43.846773 #17369]  INFO -- : [diaspora:sidekiq] => monitor  (load by user)
I, [2017-12-14T19:08:43.847271 #17369]  INFO -- : [diaspora:web] schedule :monitor (monitor by user)
I, [2017-12-14T19:08:43.847629 #17369]  INFO -- : [diaspora:sidekiq] starting async with 0.2s chain monitor 
I, [2017-12-14T19:08:43.848310 #17369]  INFO -- : [Eye] <= loading: ["/home/diaspora/diaspora/config/eye.rb"]
I, [2017-12-14T19:08:43.848991 #17369]  INFO -- : [diaspora:web] => monitor  (monitor by user)
I, [2017-12-14T19:08:43.852595 #17369]  INFO -- : [diaspora:__default__] <= monitor
W, [2017-12-14T19:08:43.911982 #17369]  WARN -- : [diaspora:web] compare_identity: fail, pid_file: '20 Nov 11:39', process: '13 Dec 20:40' (eye monitoring v0.9.2 [diaspora] (in /home/diaspora))
W, [2017-12-14T19:08:43.912141 #17369]  WARN -- : [diaspora:web] load_external_pid_file: process <1331> from pid_file failed check_identity
I, [2017-12-14T19:08:43.913167 #17369]  INFO -- : [diaspora:web] switch :starting [:unmonitored => :starting] monitor by user
I, [2017-12-14T19:08:43.853426 #17369]  INFO -- : [diaspora:sidekiq:sidekiq1] schedule :monitor (monitor by user)
I, [2017-12-14T19:08:43.913832 #17369]  INFO -- : [diaspora:web] executing: `bin/bundle exec unicorn -c config/unicorn.rb -D` with start_timeout: 15.0s, start_grace: 2.5s, env: 'RAILS_ENV=production PORT=' (in /home/diaspora/diaspora)
I, [2017-12-14T19:08:43.914567 #17369]  INFO -- : [diaspora:sidekiq:sidekiq1] => monitor  (monitor by user)
I, [2017-12-14T19:08:43.915638 #17369]  INFO -- : [diaspora:sidekiq] <= monitor
I, [2017-12-14T19:08:43.909764 #17369]  INFO -- : [Eye] <= command: load /home/diaspora/diaspora/config/eye.rb (0.468157845s)
W, [2017-12-14T19:08:43.918461 #17369]  WARN -- : [diaspora:sidekiq:sidekiq1] compare_identity: touched, pid_file: '14 Dec 19:08', process: '14 Dec 18:55' (sidekiq 5.0.4 diaspora [0 o)
I, [2017-12-14T19:08:43.919044 #17369]  INFO -- : [diaspora:sidekiq:sidekiq1] load_external_pid_file: process <16901> from pid_file found and running (identity: touched) (sidekiq 5.0.4 diaspora [0 o)
I, [2017-12-14T19:08:43.923404 #17369]  INFO -- : [diaspora:sidekiq:sidekiq1] switch :already_running [:unmonitored => :up] monitor by user
I, [2017-12-14T19:08:43.924467 #17369]  INFO -- : [diaspora:sidekiq:sidekiq1] <= monitor
I, [2017-12-14T19:08:46.167749 #17369]  INFO -- : [diaspora:web] sleeping for :start_grace 2.5
W, [2017-12-14T19:08:48.669556 #17369]  WARN -- : [diaspora:web] compare_identity: fail, pid_file: '20 Nov 11:39', process: '13 Dec 20:40' (eye monitoring v0.9.2 [diaspora] (in /home/diaspora))
W, [2017-12-14T19:08:48.669881 #17369]  WARN -- : [diaspora:web] load_external_pid_file: process <1331> from pid_file failed check_identity
E, [2017-12-14T19:08:48.672150 #17369] ERROR -- : [diaspora:web] Exception: undefined method `[]' for nil:NilClass ["/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/eye-0.9.2/lib/eye/process/commands.rb:16:in `start_process'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/eye-0.9.2/lib/eye/process/controller.rb:11:in `start'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/eye-0.9.2/lib/eye/process/controller.rb:27:in `monitor'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/eye-0.9.2/lib/eye/process/scheduler.rb:74:in `scheduler_consume'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/eye-0.9.2/lib/eye/process/scheduler.rb:126:in `scheduler_run'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'", "/home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'"]
I, [2017-12-14T19:08:48.672396 #17369]  INFO -- : [diaspora:web] <= monitor

```

```
$ git log -1
commit 2c9fec91dab38398df4448f7e8bb49a0fb4eb191
Merge: db95c94 7c46480
Author: Benjamin Neff <benjamin@coding4coffee.ch>
Date:   Wed Nov 1 00:48:47 2017 +0100

    Merge branch 'hotfix/0.7.1.1'
```
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```
```
$ uname -a
Linux odroid 3.8.13.30 #1 SMP PREEMPT Sun Feb 14 00:13:52 CET 2016 armv7l GNU/Linux
```
```
$ cat /etc/debian_version 
8.10
```

I tried to regenerate the bundle, but without luck:
```
$ gem install bundler
Successfully installed bundler-1.16.0
Parsing documentation for bundler-1.16.0
Done installing documentation for bundler after 26 seconds
1 gem installed
```
```
$ bin/bundle 
Using rake 12.1.0
Using concurrent-ruby 1.0.5
Using i18n 0.8.6
Using minitest 5.10.3
Using thread_safe 0.3.6
Using tzinfo 1.2.3
Using activesupport 5.1.4
Using builder 3.2.3
Using erubi 1.6.1
Using mini_portile2 2.3.0
Using nokogiri 1.8.1
Using rails-dom-testing 2.0.3
Using crass 1.0.2
Using loofah 2.1.1
Using rails-html-sanitizer 1.0.3
Using actionview 5.1.4
Using rack 2.0.3
Using rack-test 0.7.0
Using actionpack 5.1.4
Using nio4r 2.1.0
Using websocket-extensions 0.1.2
Using websocket-driver 0.6.5
Using actioncable 5.1.4
Using globalid 0.4.0
Using activejob 5.1.4
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using mail 2.6.6
Using actionmailer 5.1.4
Using activemodel 5.1.4
Using active_model_serializers 0.9.7
Using arel 8.0.0
Using activerecord 5.1.4
Using activerecord-import 0.20.1
Using acts-as-taggable-on 5.0.0
Using acts_as_api 1.0.1
Using public_suffix 3.0.0
Using addressable 2.5.2
Using excon 0.59.0
Using formatador 0.2.5
Using fog-core 1.45.0
Using unf_ext 0.0.7.4
Using unf 0.1.4
Using asset_sync 2.2.0
Using attr_required 1.0.1
Using execjs 2.7.0
Using autoprefixer-rails 7.1.4.1
Using bcrypt 3.1.11
Using bindata 2.4.1
Using sass 3.4.25
Using bootstrap-sass 3.3.7
Using bootstrap-switch-rails 3.3.3
Using buftok 0.2.0
Using bundler 1.16.0
Using carrierwave 1.1.0
Using hitimes 1.2.6
Using timers 4.1.2
Using celluloid-essentials 0.20.5
Using celluloid-extras 0.20.5
Using celluloid-fsm 0.20.5
Using celluloid-pool 0.20.5
Using celluloid-supervision 0.20.6
Using celluloid 0.17.3
Using celluloid-io 0.17.3
Using chunky_png 1.3.8
Using multi_json 1.12.2
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.10.2
Using ffi 1.9.18
Using rb-inotify 0.9.10
Using compass 1.0.3
Using method_source 0.8.2
Using thor 0.19.4
Using railties 5.1.4
Using sprockets 3.7.1
Using sprockets-rails 3.2.1
Using tilt 2.0.8
Using sass-rails 5.0.6
Using compass-rails 3.0.2
Using configurate 0.3.1
Using connection_pool 2.2.1
Using orm_adapter 0.5.0
Using responders 2.4.0
Using warden 1.2.7
Using devise 4.3.0
Using rails 5.1.4
Using devise_lastseenable 0.0.6
Using diaspora-prosody-config 0.0.7
Using multipart-post 2.0.0
Using faraday 0.11.0
Using faraday_middleware 0.12.2
Using ethon 0.10.1
Using typhoeus 1.3.0
Using valid 1.2.0
Using diaspora_federation 0.2.2
Using diaspora_federation-json_schema 0.2.2
Using diaspora_federation-rails 0.2.2
Using domain_name 0.5.20170404
Using entypo-rails 3.0.0
Using equalizer 0.0.11
Using et-orbi 1.0.5
Using sigar 0.7.3
Using state_machines 0.5.0
Using eye 0.9.2
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.6
Using fog-json 1.0.2
Using fog-xml 0.1.3
Using ipaddress 0.8.3
Using fog-aws 1.4.1
Using get_process_mem 0.2.1
Using json 2.1.0
Using request_store 1.3.2
Using gon 6.1.0
Using temple 0.8.0
Using hamlit 2.8.4
Using handlebars_assets 0.23.2
Using hashie 3.5.6
Using http-form_data 1.0.3
Using http_parser.rb 0.6.0
Using http 2.2.2
Using http_accept_language 2.1.1
Using httpclient 2.8.3
Using i18n-inflector 2.6.7
Using i18n-inflector-rails 1.0.7
Using jquery-rails 4.3.1
Using js-routes 1.4.1
Using js_image_paths 0.1.1
Using securecompare 1.0.0
Using url_safe_base64 0.2.2
Using json-jwt 1.7.2
Using json-schema 2.8.0
Using jwt 1.5.6
Using kgio 2.11.0
Using leaflet-rails 1.2.0
Using little-plugger 1.1.4
Using logging 2.2.2
Using logging-rails 0.6.0
Using systemu 2.6.5
Using macaddr 1.7.1
Using markerb 1.1.0
Using memoizable 0.4.2
Using mini_magick 4.8.0
Using rack-mobile-detect 0.4.0
Using mobile-fu 1.4.0
Using multi_xml 0.6.0
Using mysql2 0.4.9
Using naught 1.1.0
Using oauth 0.5.3
Using oauth2 1.4.0
Using omniauth 1.6.1
Using omniauth-oauth2 1.4.0
Using omniauth-facebook 4.0.0
Using omniauth-oauth 1.1.0
Using omniauth-tumblr 1.2
Using omniauth-twitter 1.4.0
Using omniauth-wordpress 0.2.2
Using open_graph_reader 0.6.2
Using rack-oauth2 1.6.2
Using swd 1.0.1
Using validate_email 0.1.6
Using validate_url 1.0.2
Using webfinger 1.0.2
Using openid_connect 1.1.3
Using rack-cors 1.0.1
Using rack-google-analytics 1.2.0
Using rack-piwik 0.3.0
Using rack-protection 2.0.0
Using rack-rewrite 1.5.1
Using rack-ssl 1.4.1
Using rails-assets-autosize 4.0.0
Using rails-assets-underscore 1.8.3
Using rails-assets-backbone 1.3.3
Using rails-assets-blueimp-gallery 2.27.0
Using rails-assets-jquery 3.2.1
Using rails-assets-bootstrap 3.3.7
Using rails-assets-bootstrap-markdown 2.10.0
Using rails-assets-corejs-typeahead 1.1.1
Using rails-assets-emojione 2.0.1
Using rails-assets-favico.js 0.3.10
Using rails-assets-jquery-colorbox 1.6.4
Using rails-assets-jquery-fullscreen-plugin 0.5.0
Using rails-assets-jquery.slimscroll 1.3.8
Using rails-assets-jquery.ui 1.11.4
Using rails-assets-diaspora_jsxc 0.1.5.develop.7
Using rails-assets-fine-uploader 5.13.0
Using rails-assets-highlightjs 9.12.0
Using rails-assets-jquery-placeholder 2.3.1
Using rails-assets-jquery-textchange 0.2.3
Using rails-assets-jquery.are-you-sure 1.9.0
Using rails-assets-markdown-it 8.4.0
Using rails-assets-markdown-it--markdown-it-for-inline 0.1.1
Using rails-assets-markdown-it-diaspora-mention 1.2.0
Using rails-assets-markdown-it-hashtag 0.4.0
Using rails-assets-markdown-it-sanitizer 0.4.3
Using rails-assets-markdown-it-sub 1.0.0
Using rails-assets-markdown-it-sup 1.0.0
Using rails-assets-perfect-scrollbar 0.6.16
Using rails-i18n 5.0.4
Using rails-timeago 2.16.0
Using raindrops 0.19.0
Using redcarpet 3.4.0
Using redis 3.3.3
Using ruby-oembed 0.12.0
Using rubyzip 1.2.1
Using rufus-scheduler 3.4.2
Using useragent 0.16.8
Using secure_headers 3.7.1
Using sidekiq 5.0.4
Using sidekiq-cron 0.6.3
Using simple_captcha2 0.4.3
Using simple_oauth 0.3.1
Using yard 0.9.9
Using string-direction 1.2.0
Using twitter 6.1.0
Using twitter-text 1.14.7
Using uglifier 3.2.0
Using unicorn 5.3.0
Using unicorn-worker-killer 0.4.4
Using uuid 2.3.8
Using versionist 1.6.0
Using will_paginate 3.1.6
Bundle complete! 139 Gemfile dependencies, 223 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `./vendor/bundle`
```

**Comment by goobertron** [comment]
Hi, try our [IRC channel](http://webchat.freenode.net/?channels=diaspora) for admin help. If it proves to be a bug in the software rather than something wrong in your setup, it could then be logged here in Github.

**Comment by dest4** [comment]
I tried already, but will try again.

**Comment by dest4** [comment]
Solution: a non functionnal Diaspora process was still running in a "screen". Killed it, restarted D* and now it's OK.
