### ISSUE TITLE
Error 500 when visiting /notifications

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7689]
```
[2018-01-03T17:28:37] INFO  PID-7302 TID-23392020 Rails: Started GET "/notifications" for X.X.X.X at 2018-01-03 17:28:37 +0100
[2018-01-03T17:28:37] INFO  PID-7302 TID-23392020 ActionController::Base: Processing by NotificationsController#index as HTML
[2018-01-03T17:28:37] INFO  PID-7302 TID-23392020 ActionController::Base: Completed 500 Internal Server Error in 392ms (ActiveRecord: 110.2ms)
[2018-01-03T17:28:37] FATAL PID-7302 TID-23392020 Rails:   
[2018-01-03T17:28:37] FATAL PID-7302 TID-23392020 Rails: ActionView::Template::Error (invalid date):
[2018-01-03T17:28:37] FATAL PID-7302 TID-23392020 Rails:     11:   .media-object.pull-left
    12:     = person_image_link note.actors.first, :size => :thumb_small, :class => 'hovercardable'
    13:   .media-body
    14:     = notification_message_for(note)
    15:     %div
    16:       = timeago(note.updated_at)
[2018-01-03T17:28:37] FATAL PID-7302 TID-23392020 Rails:   
[2018-01-03T17:28:37] FATAL PID-7302 TID-23392020 Rails: app/helpers/notifications_helper.rb:93:in `strptime'
app/helpers/notifications_helper.rb:93:in `locale_date'
app/helpers/notifications_helper.rb:50:in `opts_for_birthday'
app/helpers/notifications_helper.rb:20:in `object_link'
app/helpers/notifications_helper.rb:77:in `notification_message_for'
app/views/notifications/_notification.haml:14:in `_app_views_notifications__notification_haml___3417256652389374919_83805620'
app/views/notifications/index.html.haml:71:in `block (2 levels) in _app_views_notifications_index_html_haml___1645221757046757183_94675240'
app/views/notifications/index.html.haml:70:in `each'
app/views/notifications/index.html.haml:70:in `block in _app_views_notifications_index_html_haml___1645221757046757183_94675240'
app/views/notifications/index.html.haml:58:in `each'
app/views/notifications/index.html.haml:58:in `_app_views_notifications_index_html_haml___1645221757046757183_94675240'
```

@Rete2 maybe you want to have a look at that?

**Comment by netagonen** [comment]
Hi! Wow, I saw this super late and you already took care of this, Thanks :)
