### ISSUE TITLE
Templates failed, did no changes

### ISSUE THREAD

**Issue by 001101** [diaspora/diaspora#7891]
Hello,

what can I do if my templates are broken or something else in the asset pipe is missing?

I override some CSS things, imported it in the scss files and then i was figuring out how to get those assets in the system, i did following a few times:

RAILS_ENV=production bundle exec rails assets:clobber
RAILS_ENV=production bundle exec rails assets:clean
RAILS_ENV=production bundle exec rails assets:precompile

Then I also changed the logo on my pod (diaspora/app/assets/branding/logos)
But they all worked yesterday.

First thing which come up was that the branding/logos/asterisk_white_mobile.png was not found, but it was there, i changed something on templates and could not remember, so i put the original back in.

`[2018-10-13T15:28:15] INFO  PID-32105 TID-19394480 ActionController::Base: Processing by HomeController#show as HTML
[2018-10-13T15:28:15] INFO  PID-32105 TID-19394480 ActionController::Base: Completed 500 Internal Server Error in 89ms (ActiveRecord: 4.5ms)
[2018-10-13T15:28:15] FATAL PID-32105 TID-19394480 Rails:   
[2018-10-13T15:28:15] FATAL PID-32105 TID-19394480 Rails: ActionView::Template::Error (The asset "branding/logos/asterisk_white_mobile.png" is not present in the asset pipeline.):
[2018-10-13T15:28:15] FATAL PID-32105 TID-19394480 Rails:     14:                   .hidden-xs
    15:                     = link_to AppConfig.settings.pod_name, root_path, class: "navbar-brand"
    16:                   .visible-xs-block.header-title
    17:                     = link_to(image_tag("**branding/logos/asterisk_white_mobile.png**", class: "img-responsive"),
    18:                         root_path, class: "navbar-brand")
    19:                 = render "layouts/header_not_connected"
[2018-10-13T15:28:15] FATAL PID-32105 TID-19394480 Rails:   
[2018-10-13T15:28:15] FATAL PID-32105 TID-19394480 Rails: app/views/layouts/_header.html.haml:17:in `_app_views_layouts__header_html_haml__3542251370305246389_89831620'
app/views/layouts/with_header.html.haml:2:in `block in _app_views_layouts_with_header_html_haml__4381373114498847661_97260960'
app/views/layouts/with_header.html.haml:1:in `_app_views_layouts_with_header_html_haml__4381373114498847661_97260960'
app/views/layouts/with_header_with_footer.html.haml:4:in `_app_views_layouts_with_header_with_footer_html_haml__1720277477106993151_92204540'
app/controllers/home_controller.rb:25:in `show'`

**Then it worked somehow I think and the shit was moving forward:**

`[2018-10-13T15:30:23] FATAL PID-32105 TID-19394480 Rails:   
[2018-10-13T15:30:23] FATAL PID-32105 TID-19394480 Rails: app/views/layouts/_header.html.haml:17:in `_app_views_layouts__header_html_haml__3542251370305246389_85561160'
app/views/layouts/with_header.html.haml:2:in `block in _app_views_layouts_with_header_html_haml__4381373114498847661_87208320'
app/views/layouts/with_header.html.haml:1:in `_app_views_layouts_with_header_html_haml__4381373114498847661_87208320'
app/views/layouts/with_header_with_footer.html.haml:4:in `_app_views_layouts_with_header_with_footer_html_haml__1720277477106993151_92204540'
app/controllers/home_controller.rb:25:in `show'
[2018-10-13T15:30:27] INFO  PID-32105 TID-19394480 Rails: Started GET "/notifications?per_page=10&page=1&_=1539433227331" for 2400:cb00:75:1024::a29e:ca94 at 2018-10-13 15:30:27 +0200
[2018-10-13T15:30:27] INFO  PID-32105 TID-19394480 ActionController::Base: Processing by NotificationsController#index as JSON
[2018-10-13T15:30:27] INFO  PID-32105 TID-19394480 ActionController::Base:   Parameters: {"per_page"=>"10", "page"=>"1", "_"=>"1539433227331"}
[2018-10-13T15:30:27] INFO  PID-32105 TID-19394480 ActionController::Base: Completed 500 Internal Server Error in 59ms (ActiveRecord: 8.7ms)
[2018-10-13T15:30:27] FATAL PID-32105 TID-19394480 Rails:   
[2018-10-13T15:30:27] FATAL PID-32105 TID-19394480 Rails: ActionView::Template::Error (The asset "user/default.png" is not present in the asset pipeline.):
[2018-10-13T15:30:27] FATAL PID-32105 TID-19394480 Rails:      9:         .aspect-membership-dropdown.placeholder{data: {person_id: note.target.id}}
    10: 
    11:   .media-object.pull-left
    12:     = person_image_link note.actors.first, :size => :thumb_small, :class => 'hovercardable'
    13:   .media-body
    14:     = notification_message_for(note)
    15:     %div
[2018-10-13T15:30:27] FATAL PID-32105 TID-19394480 Rails:   
[2018-10-13T15:30:27] FATAL PID-32105 TID-19394480 Rails: app/models/profile.rb:70:in `image_url'`

**Then the mobile.js was missing in the asset pipeline**

`[2018-10-13T15:31:43] INFO  PID-32105 TID-19394480 ActionController::Base: Completed 500 Internal Server Error in 476ms (ActiveRecord: 53.9ms)
[2018-10-13T15:31:43] FATAL PID-32105 TID-19394480 Rails:   
[2018-10-13T15:31:43] FATAL PID-32105 TID-19394480 Rails: ActionView::Template::Error (The asset "mobile/mobile.js" is not present in the asset pipeline.):
[2018-10-13T15:31:43] FATAL PID-32105 TID-19394480 Rails:      6: %html{lang: I18n.locale.to_s, dir: (rtl? ? "rtl" : "ltr")}
     7:   %head{prefix: og_prefix}
     8:     - content_for :javascript do
     9:       = javascript_include_tag "mobile/mobile"
    10:       = load_javascript_locales
    11: 
    12:     = render "head"
[2018-10-13T15:31:43] FATAL PID-32105 TID-19394480 Rails:   
[2018-10-13T15:31:43] FATAL PID-32105 TID-19394480 Rails: app/views/layouts/application.mobile.haml:9:in `block in _app_views_layouts_application_mobile_haml___4598889698582784532_59880980'
app/views/layouts/application.mobile.haml:8:in `_app_views_layouts_application_mobile_haml___4598889698582784532_59880980'
config/initializers/devise.rb:9:in `to_mobile'
app/controllers/tags_controller.rb:43:in `show'`

I tried to change the _header.mobile.haml and _header.haml to something like that and also tried to insert skip_pipeline, but syntax was wrong or it not worked, but it not worked.

`      = link_to(image_tag("branding/logos/asterisk.png", class: "img-responsive",  skip_pipeline: true),
`

What's the point?

Regards 001101

**Comment by goobertron** [comment]
Hello,

GitHub is not a support forum; it's an issue tracker. For support issues, please post in the [podmin support section](https://discourse.diasporafoundation.org/c/support/podmin-support) of our Discourse forum.

**Comment by 001101** [comment]
@goobertron You are wrong

**Comment by denschub** [comment]
No, he is not. And since you already posted there, I will close this issue.

**Comment by 001101** [comment]
He is and I posted after he told me, postfactum century here we are!!

**Comment by denschub** [comment]
Before you contribute, comment, or somehow interact with this project any further, I'd like you to read [our community guidelines](https://diasporafoundation.org/community_guidelines), as well as our [Code of Conduct](https://github.com/diaspora/diaspora/blob/develop/CODE_OF_CONDUCT.md). If you disagree with those rules and do not want to follow them, please stop interacting with this project.

When members of the project team, clearly indicated by a "member" badge in the header of all GitHub comments, ask you in a friendly tone do do something, then they do this because our project has rules, and everyone needs to follow them. In this case, GitHub is there to track software issues and track actionable feature requests. Support requests of any kind are handled on Discourse, as this allows more people to join. If you don't like this, well, too bad. This decision has been made by the majority of our community, and we for sure will not change our work just because you feel like it.
