### ISSUE TITLE
Visiting diaspora* with `web+diaspora://` with unknown urls throws a 500

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7906]
With the release of diaspora* 0.7.7.0 users start to play with `web+diaspora://` links. Unfortunately, diaspora* crashes when the URL is unknown. 

For example, if I register the handler on my pod https://diaspora-fr.org and create a link with `web+diaspora://foo/bar`, clicking on that link will redirect me to `https://diaspora-fr.org/link?q=web%2Bdiaspora%3A%2F%2Ffoo%2Fbar` which leads to an error 500.

```
[2018-10-24T15:09:09] INFO  PID-22916 TID-3264340 Rails: Started GET "/link?q=web%2Bdiaspora%3A%2F%2Ffoo%2Fbar" for X.X.X.X at 2018-10-24 15:09:09 +0200
[2018-10-24T15:09:09] INFO  PID-22916 TID-3264340 ActionController::Base: Processing by LinksController#resolve as HTML
[2018-10-24T15:09:09] INFO  PID-22916 TID-3264340 ActionController::Base:   Parameters: {"q"=>"web+diaspora://foo/bar"}
[2018-10-24T15:09:09] INFO  PID-22916 TID-3264340 ActionController::Base: Completed 500 Internal Server Error in 9ms (ActiveRecord: 1.1ms)
[2018-10-24T15:09:09] FATAL PID-22916 TID-3264340 Rails:   
[2018-10-24T15:09:09] FATAL PID-22916 TID-3264340 Rails: NoMethodError (undefined method `[]' for nil:NilClass):
[2018-10-24T15:09:09] FATAL PID-22916 TID-3264340 Rails:   
[2018-10-24T15:09:09] FATAL PID-22916 TID-3264340 Rails: app/services/diaspora_link_service.rb:41:in `parse'
app/services/diaspora_link_service.rb:9:in `initialize'
app/controllers/links_controller.rb:5:in `new'
app/controllers/links_controller.rb:5:in `resolve'
```

**Comment by HankG** [comment]
What is the expected behavior for this error workflow?

**Comment by SuperTux88** [comment]
I think it should display a 404 instead of a 500.
