### ISSUE TITLE
Migration import stops on different issues

### ISSUE THREAD

**Issue by tclaus** [diaspora/diaspora#8256]
Some Issues while importing a random migration file

rails aborted!
DiasporaFederation::Federation::Fetcher::NotFetchable: Failed to fetch Post:6036f0c5f9f5f09761ab3ed9b3e1f03b8695d1b8 from neo@friendica.produnis.de: RuntimeError: Failed to fetch https://friendica.produnis.de/fetch/post/6036f0c5f9f5f09761ab3ed9b3e1f03b8695d1b8: 404
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/diaspora_federation-0.2.6/lib/diaspora_federation/federation/fetcher.rb:15:in `rescue in fetch_public'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/diaspora_federation-0.2.6/lib/diaspora_federation/federation/fetcher.rb:10:in `fetch_public'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/diaspora_federation-0.2.6/lib/diaspora_federation/entities/related_entity.rb:43:in `fetch'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/diaspora_federation-0.2.6/lib/diaspora_federation/entities/reshare.rb:54:in `validate_root'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/diaspora_federation-0.2.6/lib/diaspora_federation/entities/reshare.rb:66:in `tap'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/diaspora_federation-0.2.6/lib/diaspora_federation/entities/reshare.rb:66:in `from_hash'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/diaspora_federation-0.2.6/lib/diaspora_federation/entity.rb:124:in `from_json'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/entity_importer.rb:27:in `entity'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/entity_importer.rb:14:in `import'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/own_entity_importer.rb:7:in `import'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/post_importer.rb:8:in `import'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:91:in `block in import_collection'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:90:in `each'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:90:in `import_collection'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:78:in `import_posts'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:17:in `import'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/app/services/migration_service.rb:37:in `import_archive'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/app/services/migration_service.rb:20:in `perform!'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/tasks/accounts.rake:22:in `block (2 levels) in <top (required)>'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/railties-5.2.5/lib/rails/command.rb:48:in `invoke'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

**Comment by tclaus** [comment]
rails aborted!
NoMethodError: undefined method `author' for nil:NilClass
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/own_entity_importer.rb:28:in `real_author'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/own_entity_importer.rb:24:in `persisted_object'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/post_importer.rb:9:in `import'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:91:in `block in import_collection'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:90:in `each'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:90:in `import_collection'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:78:in `import_posts'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:17:in `import'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/app/services/migration_service.rb:37:in `import_archive'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/app/services/migration_service.rb:20:in `perform!'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/tasks/accounts.rake:22:in `block (2 levels) in <top (required)>'

**Comment by tclaus** [comment]
rails aborted!
DiasporaFederation::Entity::ValidationError: Like:fd9e3e70f9980138cf4f047d7b62795e from tclaus@localhost:3000: Missing required properties: parent
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/diaspora_federation-0.2.6/lib/diaspora_federation/entity.rb:205:in `validate_missing_props'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/diaspora_federation-0.2.6/lib/diaspora_federation/entity.rb:65:in `initialize'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6@diaspora/gems/diaspora_federation-0.2.6/lib/diaspora_federation/entities/relayable.rb:70:in `initialize'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/own_relayable_importer.rb:7:in `new'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/own_relayable_importer.rb:7:in `entity'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/entity_importer.rb:14:in `import'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer/own_entity_importer.rb:7:in `import'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:91:in `block in import_collection'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/lib/archive_importer.rb:90:in `each'

**Comment by tclaus** [comment]
rails aborted!
Workers::SendBase::MaxRetriesReached: Workers::SendBase::MaxRetriesReached
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/app/workers/send_base.rb:16:in `schedule_retry'
/Users/thorstenclaus/Documents/develop/web-projects/diaspora/app/workers/send_public.rb:10:in `perform'


The local dev machine can not send to remote hosts, which is OK I think, but should the migration be aborted then? Better catch it and write a warning?

**Comment by tclaus** [comment]
Migration runs now relative fail save in Rake Task - should I commit code?

**Comment by tclaus** [comment]
User -Blocks are not implemented

**Comment by tclaus** [comment]
Hopefully fixed with 9723bd37a78ed65c365835204ee699f981461106 and 1ec031475260d513661620ac52b799cffc3f544e
