### ISSUE TITLE
notifications crash diaspora

### ISSUE THREAD

**Issue by norayr** [diaspora/diaspora#8367]
hello,
i am using diaspora from 'develop' branch, v0.7.99.0, [source code](https://spyurk.am/source.tar.gz)

when entering notifications we get this error:

```
ERROR PID-23063 TID-47233707743580 Api::V1::NotificationsController: undefined local variable or method `guid' for #<Notifications::AlsoCommented:0x000055eaf1f1d7e0>
```

more detailed log:

```
[2022-07-19T14:35:55] INFO  PID-12607 TID-47233707743580 Rails: Started GET "/posts/1312572/comments/new" for 114.119.135.251 at 2022-07-19 14:35:55 +0400
[2022-07-19T14:35:55] INFO  PID-12607 TID-47233707743580 ActionController::Base: Processing by CommentsController#new as HTML
[2022-07-19T14:35:55] INFO  PID-12607 TID-47233707743580 ActionController::Base:   Parameters: {"post_id"=>"1312572"}
[2022-07-19T14:35:55] INFO  PID-12607 TID-47233707743580 ActionController::Base: Completed 401 Unauthorized in 5ms (ActiveRecord: 0.0ms)
[2022-07-19T14:35:56] INFO  PID-23063 TID-47233707743580 Rails: Started GET "/api/v1/notifications?only_unread=false" for 46.36.116.23 at 2022-07-19 14:35:56 +0400
[2022-07-19T14:35:56] INFO  PID-23063 TID-47233707743580 ActionController::Base: Processing by Api::V1::NotificationsController#index as HTML
[2022-07-19T14:35:56] INFO  PID-23063 TID-47233707743580 ActionController::Base:   Parameters: {"only_unread"=>"false"}
[2022-07-19T14:35:56] ERROR PID-23063 TID-47233707743580 Api::V1::NotificationsController: undefined local variable or method `guid' for #<Notifications::AlsoCommented:0x000055eaf1f1d7e0>
[2022-07-19T14:35:56] ERROR PID-23063 TID-47233707743580 Api::V1::NotificationsController: /home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.7.1/lib/active_model/attribute_methods.rb:430:in `method_missing'
/home/srv/spyurk/diaspora/lib/diaspora/fields/guid.rb:16:in `set_guid'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:517:in `block in invoke_after'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:517:in `each'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:517:in `invoke_after'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:133:in `run_callbacks'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:816:in `_run_initialize_callbacks'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/core.rb:348:in `init_with'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/persistence.rb:71:in `instantiate'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/querying.rb:52:in `block (2 levels) in find_by_sql'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/result.rb:57:in `block in each'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/result.rb:57:in `each'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/result.rb:57:in `each'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/querying.rb:52:in `map'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/querying.rb:52:in `block in find_by_sql'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/querying.rb:51:in `find_by_sql'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/relation.rb:560:in `block in exec_queries'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/relation.rb:547:in `exec_queries'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/relation.rb:422:in `load'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/relation.rb:200:in `records'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/relation/delegation.rb:71:in `each'
/home/srv/spyurk/diaspora/lib/api/paging/time_paginator.rb:30:in `map'
/home/srv/spyurk/diaspora/lib/api/paging/time_paginator.rb:30:in `page_data'
/home/srv/spyurk/diaspora/lib/api/paging/time_paginator.rb:54:in `previous_page'
/home/srv/spyurk/diaspora/lib/api/paging/rest_paged_response_builder.rb:28:in `navigation_builder'
/home/srv/spyurk/diaspora/lib/api/paging/rest_paged_response_builder.rb:20:in `response'
/home/srv/spyurk/diaspora/app/controllers/api/v1/notifications_controller.rb:30:in `index'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/abstract_controller/base.rb:194:in `process_action'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `block in instrument'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `instrument'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/abstract_controller/base.rb:134:in `process'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.7.1/lib/action_view/rendering.rb:32:in `process'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_controller/metal.rb:191:in `dispatch'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_controller/metal.rb:252:in `dispatch'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/journey/router.rb:35:in `each'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/journey/router.rb:35:in `serve'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/omniauth-2.0.4/lib/omniauth/builder.rb:45:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-mobile-detect-0.4.0/lib/rack/mobile-detect.rb:164:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-oauth2-1.19.0/lib/rack/oauth2/server/resource.rb:20:in `_call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-oauth2-1.19.0/lib/rack/oauth2/server/resource/bearer.rb:8:in `_call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-oauth2-1.19.0/lib/rack/oauth2/server/abstract/handler.rb:17:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/versionist-2.0.1/lib/versionist/middleware.rb:39:in `_call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/versionist-2.0.1/lib/versionist/middleware.rb:17:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/simple_captcha2-0.5.0/lib/simple_captcha/middleware.rb:47:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/railties-5.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/railties-5.2.7.1/lib/rails/rack/logger.rb:28:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.7.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/secure_headers-6.3.3/lib/secure_headers/middleware.rb:11:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/railties-5.2.7.1/lib/rails/engine.rb:524:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/railties-5.2.7.1/lib/rails/railtie.rb:190:in `public_send'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/railties-5.2.7.1/lib/rails/railtie.rb:190:in `method_missing'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/show_exceptions.rb:23:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/chunked.rb:98:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/http_server.rb:634:in `process_client'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-worker-killer-0.4.5/lib/unicorn/worker_killer.rb:53:in `process_client'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/http_server.rb:732:in `worker_loop'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/http_server.rb:547:in `spawn_missing_workers'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/http_server.rb:561:in `maintain_worker_count'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/http_server.rb:294:in `join'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/bin/unicorn:128:in `<top (required)>'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `load'
/home/srv/spyurk/diaspora/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `<top (required)>'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:463:in `exec'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:18:in `start'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/home/srv/spyurk/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
bin/bundle:3:in `load'
bin/bundle:3:in `<main>'
[2022-07-19T14:35:56] INFO  PID-23063 TID-47233707743580 ActionController::Base: Completed 500 Internal Server Error in 54ms (Views: 0.4ms | ActiveRecord: 39.6ms)
[2022-07-19T14:35:56] INFO  PID-23063 TID-47233707743580 Rails: Started GET "/users/sign_in.mobile" for 114.119.135.251 at 2022-07-19 14:35:56 +0400
[2022-07-19T14:35:56] INFO  PID-23063 TID-47233707743580 ActionController::Base: Processing by SessionsController#new as MOBILE
[2022-07-19T14:35:56] INFO  PID-23063 TID-47233707743580 ActionController::Base: Completed 200 OK in 42ms (Views: 36.5ms | ActiveRecord: 0.0ms)
[2022-07-19T14:35:57] INFO  PID-23063 TID-47233707743580 Rails: Started GET "/tags/verschwendung?max_time=1378242962" for 114.119.128.132 at 2022-07-19 14:35:57 +0400
[2022-07-19T14:35:57] INFO  PID-23063 TID-47233707743580 ActionController::Base: Processing by TagsController#show as HTML
[2022-07-19T14:35:57] INFO  PID-23063 TID-47233707743580 ActionController::Base:   Parameters: {"max_time"=>"1378242962", "name"=>"verschwendung"}
[2022-07-19T14:35:58] INFO  PID-23063 TID-47233707743580 ActionController::Base: Completed 200 OK in 155ms (Views: 76.4ms | ActiveRecord: 75.9ms)
[2022-07-19T14:35:59] INFO  PID-12607 TID-47233707743580 Rails: Started GET "/posts/2221273" for 114.119.140.235 at 2022-07-19 14:35:59 +0400
[2022-07-19T14:35:59] INFO  PID-12607 TID-47233707743580 ActionController::Base: Processing by PostsController#show as HTML
[2022-07-19T14:35:59] INFO  PID-12607 TID-47233707743580 ActionController::Base:   Parameters: {"id"=>"2221273"}
[2022-07-19T14:35:59] INFO  PID-12607 TID-47233707743580 ActionController::Base: Completed 200 OK in 45ms (Views: 34.6ms | ActiveRecord: 3.7ms)
[2022-07-19T14:36:00] INFO  PID-12607 TID-47233707743580 Rails: Started GET "/tags/safer?_=1656288000000" for 66.249.66.142 at 2022-07-19 14:36:00 +0400
[2022-07-19T14:36:00] INFO  PID-12607 TID-47233707743580 ActionController::Base: Processing by TagsController#show as JSON
[2022-07-19T14:36:00] INFO  PID-12607 TID-47233707743580 ActionController::Base:   Parameters: {"_"=>"1656288000000", "name"=>"safer"}
[2022-07-19T14:36:00] INFO  PID-12607 TID-47233707743580 ActionController::Base: Completed 200 OK in 147ms (Views: 95.4ms | ActiveRecord: 36.4ms)
```

if there's more information i can provide, please let me know.

**Comment by Flaburgan** [comment]
Hello, locally I can navigate to `http://localhost:3000/notifications` without problems. Here you are requesting the API route. Are you doing that with the "insporation" app?

**Comment by norayr** [comment]
hello! yes, both with insporation and the web interface.

just did it in web interface, desktop mode:

```
[2022-07-26T02:54:10] INFO  PID-368 TID-47233707743580 Rails: Started GET "/notifications?per_page=10&page=1&_=1658356293510" for 46.36.114.211 at 2022-07-26 02:54:10 +0400
[2022-07-26T02:54:10] INFO  PID-368 TID-47233707743580 ActionController::Base: Processing by NotificationsController#index as JSON
[2022-07-26T02:54:10] INFO  PID-368 TID-47233707743580 ActionController::Base:   Parameters: {"per_page"=>"10", "page"=>"1", "_"=>"1658356293510"}
[2022-07-26T02:54:10] INFO  PID-368 TID-47233707743580 ActionController::Base: Completed 500 Internal Server Error in 55ms (ActiveRecord: 37.2ms)
[2022-07-26T02:54:10] FATAL PID-368 TID-47233707743580 Rails:
[2022-07-26T02:54:10] FATAL PID-368 TID-47233707743580 Rails: NameError (undefined local variable or method `guid' for #<Notifications::AlsoCommented:0x000055eaf2f116b0>):
[2022-07-26T02:54:10] FATAL PID-368 TID-47233707743580 Rails:
[2022-07-26T02:54:10] FATAL PID-368 TID-47233707743580 Rails: lib/diaspora/fields/guid.rb:16:in `set_guid'
app/controllers/notifications_controller.rb:41:in `block in index'
app/controllers/notifications_controller.rb:34:in `index'
```

**Comment by norayr** [comment]
when did you last update your pod? maybe the code got broken after you last updated your pod. i did it recently, at july 7 or 6  i guess.

**Comment by norayr** [comment]
i am closing this because it was the error on my side. discussed today in chat.
